### ISSUE TITLE
Option for output if font passes

### ISSUE THREAD

**Issue by benkiel** [khaledhosny/ots#100]
Running ot-sanitise on the command line is frustrating if you want conformation that something passes. Can the command line version emit that a font passes? My apologies if this has been asked before or if I'm missing it, I looked through the issues and didn't see a title along these lines.

**Comment by khaledhosny** [comment]
You can check the return code it returns zero for success and non-zero for failure, the standard behaviour of Unix commands.

**Comment by benkiel** [comment]
I know one can, but that's a bit fussy and not intuitive for folks just running it on the command line to check a font. i.e., If you want type designers to check their fonts with OTS, saying "My_Awesome_Sans.ttf passes OTS" is much nicer for the user than a new prompt.

**Comment by khaledhosny** [comment]
When there is a failure we fail loudly. Anyway the tool just grew out it was not planned to be a lint tool initially, it was actually used to run a test suite, among other tools and I extended it a bit to check my fonts and so on. I don’t mind adding a message in case of success.

**Comment by benkiel** [comment]
That would be very helpful — it's good to know that the library is working. I do understand why it doesn't and where it came from, so, many thanks for considering this.

**Comment by behdad** [comment]
If you are going to make it write something, you might as well make it
verbose: write out which tables it sanitized, which it dropped, which it
bypassed, etc.  Add a -q for quiet.

On Wed, Apr 27, 2016 at 1:44 PM, Ben Kiel <notifications@github.com> wrote:

> That would be very helpful — it's good to know that the library is
> working. I do understand why it doesn't and where it came from, so, many
> thanks for considering this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/khaledhosny/ots/issues/100#issuecomment-215222225>
>



-- 
behdad
http://behdad.org/

**Comment by benkiel** [comment]
For the audience I'm thinking of (font developers) it's enough info to know it passes, what tables it drops might be helpful, but perhaps not necessary. I'm just asking for some feedback that all is well with the font.

**Comment by HinTak** [comment]
This should be a very simple enhancement: just before it ends and returns, insert something similar to this (pseudo-code, not meant to be real):
```
if (return_code == okay)
 say_something();
...
return return_code;
```

**Comment by HinTak** [comment]
Your `main()` is quite simple. Something like this should do:

```
diff --git a/util/ot-sanitise.cc b/util/ot-sanitise.cc
index a9905bf..1d243fe 100644
--- a/util/ot-sanitise.cc
+++ b/util/ot-sanitise.cc
@@ -79,6 +79,10 @@ int main(int argc, char **argv) {
   if (!result) {
     std::fprintf(stderr, "Failed to sanitise file!\n");
   }
+  else
+  {
+    std::fprintf(stderr, "file okay!\n");
+  }
 
   delete[] data;
   return !result;
```
