### ISSUE TITLE
Macintosh Unicode cmap (Platform ID = 0, Encoding ID = 3, Format = 4) support.

### ISSUE THREAD

**Issue by HinTak** [khaledhosny/ots#106]
Spent hours trying to figure out why recent firefox silently ignore a web font, which forefox 43 happily uses.

In reality it is just a perfectly valid font with a Macintosh Unicode 2.0 cmap (Platform ID = 0, Encoding ID = 3, Format = 4) . And to be honest, for small fonts supporting european languages only, or even English glyphs only,  Mac unicode (Platform ID = 0, Encoding ID = 3) and MS Unicode (Platform ID = 3, Encoding ID = 1) are equivalent.

**Comment by khaledhosny** [comment]
Do you have a font to test with?

**Comment by khaledhosny** [comment]
Also if OTS couldn’t find a suitable cmap, it would have rejected the font even in Firefox 43.

**Comment by HinTak** [comment]
Well, if you have a working web font example, you can "break" it between firefox 43 and firefox 44 by changing Platform ID = 3, Encoding ID = 1 cmap's to  Platform ID = 0, Encoding ID = 3 .

**Comment by khaledhosny** [comment]
That can be a Firefox bug, why it has to be an OTS bug if you got not OTS messages?

**Comment by HinTak** [comment]
That's true - I'll wait to see what the firefox people say ( https://bugzilla.mozilla.org/show_bug.cgi?id=1269187 ). The breakage is between ff43 and ff44, and can be 'worked around' by duplicating the Platform ID = 0, Encoding ID = 3 cmap to Platform ID = 3, Encoding ID = 1 . That's all I have for now.
