### ISSUE TITLE
ots-validate being quiet about not finding a usable cmap.

### ISSUE THREAD

**Issue by HinTak** [khaledhosny/ots#107]
Recent firefox (44+) refuses to use the font ( https://github.com/khaledhosny/ots/issues/106 ) but ots-validate says nothing.

Well, it should behave consistently - accept it, or reject it loudly.

**Comment by khaledhosny** [comment]
You mean ots-sanitise? Well if it says nothing then it considers the font valid.

**Comment by HinTak** [comment]
But firefox 44+ won't take it :-(.
