### ISSUE TITLE
a font with sbix but without glyf should not be rejected

### ISSUE THREAD

**Issue by jungshik** [khaledhosny/ots#108]
Currently, a font with both CBDT and CBLC (that are passed through) is allowed even when there's no glyf/loca table. 

That's not the case of a font with sbix table but without glyf table. One line fix would make this work, too.

**Comment by behdad** [comment]
I'm actually not sure how good of an idea this is.  Apple's specification and possibly implementation expects sbix fonts to have glyf table.  FreeType implementation doesn't.

**Comment by khaledhosny** [comment]
I didn’t know that, I just tested with FreeType. We should revert this then.

**Comment by behdad** [comment]
Since Jungshik seems to have a font, maybe he can test with Apple.

**Comment by jungshik** [comment]
In short, let's revert it.  Sorry that I hadn't tested on Mac before making a pull request (I meant to). I've just tested my hacked version of FruityGirl (only U+002[0A] supported) on Mac with Safari and Chrome (my build that passes through sbix).  

More details (still more testing is necessary): 

Safari does not like FruityGirl_sbix without glyf/loca when served as a webfont (no more details in Inspector/console).  Neither does Chrome on Mac (that passes a sbix font without glyf/loca; Blink gave me an decoding error after OTS passes it down to the OS). 

 OTOH, Safari does use the color bitmap for U+002A when FruityGirl_sbix with a nominal glyf table.  Moreover, its interpretation of BearingY seems to be different from the spec(FreeType's interpretation when tested inside Blink seems to match my reading of the spec.)  Chrome on Mac picks up a nominal outline in glyf table instead of using the bitmap in sbix table. 

I haven't yet tested either of them as a local font (as opposed to a web font).

**Comment by jungshik** [comment]
FYI, attached is a zip file with two FruityGirl_sbix fonts  (hacked to cover only U+002[0A] in sbix). One has a nominal glyf table while the other does not. 

[FruityGirl_sbix.zip](https://github.com/khaledhosny/ots/files/247522/FruityGirl_sbix.zip)

**Comment by khaledhosny** [comment]
OK, reverted.

**Comment by behdad** [comment]
Thanks Jungshik.  Please file a bug against Chrome so we figure out what to do when glyf table is present.  Alternatively we might ask OTS to drop glyf table if sbix is present.  That's a gross hack :D.

How come Chrome works with Apple Color Emoji then?

**Comment by jungshik** [comment]
@behdad With FreeType (Chrome on Linux/Android), a sbix font with and without glyf table works as intended.  I was about to write a script to convert a CBDT/CBCL font - e.g. Noto Color Emoji or FruityGirl - to a sbix font, but a failure on Mac Chrome stopped me from going forward with that. 

In Chrome on Mac (that uses Mac's internal API), my hacked sbix font is problematic while one made by Roel N works fine. So, I can't blame Chrome, yet.

**Comment by DeeDeeG** [comment]
Sorry for being off topic for a second here:

@jungshik There are no freely licensed SBIX fonts out there, that I am aware of. Is there a chance that these Fruitygirl test fonts can be released with a sharing-friendly license somewhere? 

(I would be willing to set up a simple repo if you don't have the time and if you give the written OK. Otherwise, I would like to link folks here to obtain this font, without my actually having to re-distribute it myself.)

Why I'm asking: I'm making a cross-browser color font support test that's more inspectable and reproducible than anything else I've found, but in order for people to reproduce the results, I prefer font files I can distribute. Fonts I can't distribute I write instructions for where/how to get them, but obviously distributing them in my repo is more convenient for everyone involved.

I still don't have a freely re-distributable SBIX font, and so being able to use this font would be much appreciated. Thank you for your consideration.

**Comment by khaledhosny** [comment]
See https://github.com/RoelN/ChromaCheck

**Comment by DeeDeeG** [comment]
Thank you for the reply. I'm familiar with ChromaCheck and I'd still like to go forward with my project.

My test supports the big three fonts (Segoe UI Emoji, Apple Color Emoji, Noto Color Emoji) and a very reliable and relatively popular SVG font (eosrei's Twemoji Color Font) to test all four formats...

And strives to ship at least one open-source free-to-share font for each format. I think this is both more easily inspectable/verifiable to font noobs (like myself TBH!), and also more likely to flag real-world issues with real-world fonts than ChromaCheck is. 

To contrast, ChromaCheck can help web developers serve only whichever format is supported by a visitor, which my test cannot do and does not attempt to do. I am focused on having a reliable benchmark against which to track browser progress, especially so I can file bugs against the various browsers for their lack of support. (If they can't prove they've got a problem, or can't prove that they've fixed the problem, any bug report I file would stall out.)

I think both projects have their purposes. I don't want to replace ChromaCheck, and I don't think ChromaCheck, as-is, can replace my test either.

I notice that RoelN has some test fonts at https://github.com/RoelN/color-font-test, including an SBIX one. I'm not sure which of these test fonts (his or @jungshik's) are formatted the way that will become standard practice, so maybe I should try to include both?

Anyways, I'm already decided on going forward with my project, and ChromaCheck doesn't fill the same niche. I will probably recommend and link to it for actual web development purposes, but as I said, I think it serves a different purpose (has a different focus) than my test.
