### ISSUE TITLE
Parse failure when configuring glyf/loca for passthrough

### ISSUE THREAD

**Issue by drott** [khaledhosny/ots#114]
When the table action OTS context callback is configured to do return action passthrough for glyf or loca tables, OTS will fail to add font->glyf, and thus in the end return 

`no supported glyph shapes table(s) present`
`glyf: Missing maxp or loca or head table needed by glyf table`

even though these errors do not directly result from an invalid font file, but from an undesired configuration or unsupported feature: there is no glyf or loca passthrough.

I believe this should be fixed by either adding a valid passthrough implementation for those, or by at least warning that loca / glyf were configured for passthrough.

**Comment by khaledhosny** [comment]
Passing through both `glyf` and `loca` tables should work now, I didn’t try supporting just passing though one of them as it does not seem to make much sense, but it souldn’t be had to do if really needed.
