### ISSUE TITLE
Add new test fonts

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#118]
To ensure the effectiveness of OpenType Sanitizer during further development by running the tool against those test fonts using Travis CI

We currently test quite a few fonts available in Ubuntu in Travis and we can add more tests fonts, especially from bug reports

**Comment by khaledhosny** [comment]
I have added few fonts from oss-fuzzing corpus, as well as bad fonts from bug reports. More fonts won’t hurt, but I’m not sure where to get more fonts that would be actually useful.
