### ISSUE TITLE
Sanitizing GSUB/GPOS/GDEF?

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#119]
We currently either accept them or outright reject these tables, but to do proper sanitization, we need a complete writer for layout tables. 

This is non-trivial, and may not be worth it since both Chrome and Firefox just pass-thru these tables and rely on HarfBuzz to sanitize them. 

One idea is to refactor support for GSUB, GPOS, GDEF, MATH, JSTF, and BASE tables by investigating linking with harfbuzz, which already processes these tables, but it is not clear that it can produce fixed forms as it merely sanitizes the structures in memory as it goes, and does not support writing them back. 

(Today on platforms where harfbuzz is used, Chrome does not use the OTS checks for these tables because harfbuzz does this.)

**Comment by khaledhosny** [comment]
I don’t think we are going to do this.
