### ISSUE TITLE
Zero-contour Truetype fonts?

### ISSUE THREAD

**Issue by crlf0710** [khaledhosny/ots#120]
Hi, recently i found that some specific machine-generated fonts cannot be used by Chrome, Firefox, etc...(worked ok on IE though). With the console diagnostic message, i found that it is banned with a ots sanitize failure. Then i step down to this code:
https://github.com/khaledhosny/ots/blob/master/src/glyf.cc#L110-L113 
````
  const uint32_t gly_header_length = 10 + num_contours * 2 + 2;
  if (gly_length < (gly_header_length + bytecode_length)) {
    return OTS_FAILURE_MSG("Glyph header length too high %d", gly_header_length);
  }
````
In this file, there's a glyph whose ````num_contours```` is zero, so that there's no glyph data associated with it, and the gly_header_length is 10 (the same as what the TT spec says though). Then OTS marks it as failure. Is this by design? or is this a bug?.

Thanks in advance.

**Comment by khaledhosny** [comment]
Can you attach such a font? This seems similar (but slightly different) to #52. I think the simplest is to fix the other issue and for your tool to drop `glyf` entirely if it has no contours, but we need to find if fonts without `glyf` table will work on Windows or not.

**Comment by khaledhosny** [comment]
Disregard my previous comment, this is a case of empty glyph not table. I still need a test font to check.

**Comment by behdad** [comment]
Technically, from the spec's point of view, a `numContours` of 0 is invalid.  "Simple" glyphs are specified as having `numContours > 0` while "Composite" glyphs have `numContours == -1`. A glyph with no contours is supposed to be encoded by having no glyph data at all.

If we want to support `numContours == 0` however, most natural is to assume a "Simple" glyph, in which case an `instructionLength` number is also expected.  That's where the extra 2 bytes come from.

So, I agree better to fix the subsetter. On the other hand, it's unambiguous what the intent is in this case.  IMO if any glyph header is too short, we should just drop that glyph, not reject the font.

**Comment by crlf0710** [comment]
> a numContours of 0 is invalid. "Simple" glyphs are specified as having numContours > 0 while "Composite" glyphs have numContours == -1

@behdad  No i don't think it's the case. See [the reference manual](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6glyf.html), it says.

> If a glyph has zero contours, it need not have any glyph data.

It's "need" not "shall" here, which means the zero case is still valid. Besides, 

> If the number of contours is positive or zero, it is a single glyph;

Here the spec initiatively allows the case where the number of contours is zero here. So it is allowed from the spec's point of view.

While i also agree that the situation is rare and doesn't make a lot of sense here, i think sanitizers shall follow the spec and shall not reject fonts following closely to the spec.

**Comment by crlf0710** [comment]
I've upload the font file at 
https://www.dropbox.com/s/o0vbll2clvbg944/2.woff?dl=0

**Comment by behdad** [comment]
> @behdad No i don't think it's the case. See the reference manual, it says.

Except that the current reference is OpenType standard, not Apple TrueType.

**Comment by behdad** [comment]
https://www.microsoft.com/typography/otspec/glyf.htm

**Comment by crlf0710** [comment]
> https://www.microsoft.com/typography/otspec/glyf.htm

It also says:
> int16  |   numberOfContours  |  If the number of contours is greater than or equal to zero, this is a single glyph; if negative, this is a composite glyph.
that's consistent.

**Comment by khaledhosny** [comment]
The spec is rather unclear about when the `numberOfContours` is zero, though. Should that be treated as simple glyph, in which case `instructionLength` should be present which mean OTS is right (the missing two bytes are for `instructionLength`). Or should it be treated as a special “empty glyph” case that should have no data after the header?

If you are doing this to save bytes, then you are wasting 10 bytes per empty glyph already, you shoukd just not output any data for empty glyphs at all.

Now I remember that WOFF2 outright disallows zero `numberOfContours`.

**Comment by crlf0710** [comment]
@khaledhosny Thanks for the reply. Nah i don't really know what others deal with it, but let's take the spec word by word.

It occurs to me like this:
````
Glyph ::= SingleGlyph | CompositeGlyph
SingleGlyph ::= ZeroContourGlyph | SimpleGlyph
````
**Simple Glyph Description** occurs only when the glyph is SimpleGlyph.
**Composite Glyph Description** occurs when the glyph is CompositeGlyph.

For the ZeroContourGlyph case, there's no more descriptions.

There's nothing really inconsistent in the spec, right?

> If you are doing this to save bytes, then you are wasting 10 bytes per empty glyph already, you shoukd just not output any data for empty glyphs at all.

While i agree with you on this, actually i'm not subsetting fonts by myself, i'm trying to write a tool that takes some already subsetted fonts, mends the cmaps of them and converts them to WOFF1 to be used inside the browsers. This file is one of them and it looks already like this. 

I don't really want to bother rewriting the glyf section in this case because i think it actually is following the spec, only rejected by this sanitizer (it's actually a great one overall) used by Firefox and Chrome. 

What do you think?

**Comment by khaledhosny** [comment]
I’m not entirely convinced, but like Behdad said it is unambiguous. I’m simply going to drop glyphs with 0 of contours from the `glyf` table.
