### ISSUE TITLE
If maxp and loca disagree on number of glyphs, trust loca

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/ots#124]
See https://github.com/khaledhosny/ots/issues/12#issuecomment-289408189

**Comment by behdad** [comment]
This makes me uncomfortable, but I don't really care.

**Comment by khaledhosny** [comment]
I feel a bit uneasy about it, too.

**Comment by rsheeter** [comment]
I'd like to join the uneasy club. My gut says rejection​ is more
appropriate though I understand we generally favor a kinder more forgiving
OTS these days.

**Comment by behdad** [comment]
I think it should be the other way around: if there's too many bytes in loca, ignore them.  If there's too few, assume empty glyphs at the end.
