### ISSUE TITLE
ots-idempotent.exe not created on Windows

### ISSUE THREAD

**Issue by miguelsousa** [khaledhosny/ots#127]
I can't get the build process to create `ots-idempotent.exe` on Windows.
I've tried both `./configure` and `./configure --enable-debug` options.
What am I missing?

**Comment by khaledhosny** [comment]
Does [this commit](https://github.com/khaledhosny/ots/commit/cbaf578eeda2252b2016952da3c42a9580459406) help? MSVC is giving cryptic errors when [building this on AppVeyor](https://ci.appveyor.com/project/khaledhosny/ots/build/1.0.271), I suspect it is a missing header but I can’t build on Windows right now to figure it out.

**Comment by miguelsousa** [comment]
It did help. `ots-idempotent.exe` is now building on Windows.
The tool runs, but it doesn't seem to like good fonts, see below.
```sh
$ ./ots-idempotent.exe tests/fonts/good/942fab6918c0dc9bf59f62ab15e3fd38736bbe8d.ttf
Can't verify the transcoded font on this platform.
Failed to verify the original font
```
It seems to do the right thing for bad fonts tho.
```sh
$ ./ots-idempotent.exe tests/fonts/bad/5c67809a0d4b9a16d9eba881282f920153b761eb.otf
ERROR: CFF : invalid table offset
Failed to sanitize file!
```

**Comment by khaledhosny** [comment]
Can you try again now?

**Comment by miguelsousa** [comment]
Now it doesn't build. I did `make clean` first.
```sh
CXXLD    ots-idempotent.exe
util/ots-idempotent.o:ots-idempotent.cc:(.text+0x216): undefined reference to `__imp_AddFontMemResourceEx'
util/ots-idempotent.o:ots-idempotent.cc:(.text+0x216): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_AddFontMemResourceEx'
util/ots-idempotent.o:ots-idempotent.cc:(.text+0x238): undefined reference to `__imp_RemoveFontMemResourceEx'
util/ots-idempotent.o:ots-idempotent.cc:(.text+0x238): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_RemoveFontMemResourceEx'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1247: ots-idempotent.exe] Error 1
make[1]: Leaving directory '/c/python/ots'
make: *** [Makefile:947: all] Error 2
```

**Comment by khaledhosny** [comment]
Of course, what about now?

**Comment by miguelsousa** [comment]
This is resolved. I used the `master` branch. You can nuke the `windows-idempotent` branch.

**Comment by khaledhosny** [comment]
Thanks @miguelsousa for confirming this. The `windows-idempotent` branch is gone already.
