### ISSUE TITLE
Eliminate the requirement for C++ RTTI

### ISSUE THREAD

**Issue by jfkthame** [khaledhosny/ots#129]
I notice that the new(ish) Table API now being used in OTS depends on RTTI being enabled, to allow the use of `dynamic_cast<...>`.

This is a problem at least for Gecko, which integrates OTS but is built with -fno-rtti. As such, the latest OTS code can't readily be dropped into Gecko (we're currently on 5.1.0, which predates the new Table API).

AFAICS, the use of RTTI is quite limited in scope, and I think it could be avoided without too much pain. Is this something you'd be willing to consider?

**Comment by khaledhosny** [comment]
If you have a patch to fix this it would be very helpful, otherwise I’ll try to look into this issue once I have time.
