### ISSUE TITLE
Relax GSUB/GPOS DFLT table requirements

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#131]
See:
http://typedrawers.com/discussion/comment/29427/#Comment_29427

**Comment by behdad** [comment]
Ie. Allow NULL DefaultLangSys, and non-zero LangSysCount.

**Comment by khaledhosny** [comment]
The updated spec still requires non-NULL DefaultLangSys, though allowing non-zero LangSysCount. I think most (all?) fonts being rejected by OTS here are affected by the non-zero LangSysCount.
