### ISSUE TITLE
autogen "No git found" message can be misleading

### ISSUE THREAD

**Issue by felipesanches** [khaledhosny/ots#154]
Here:

https://github.com/khaledhosny/ots/blob/master/autogen.sh#L5

It should say something like: "This autogen.sh script must be run on a working copy of the ots git repo, but a .git folder was not found (or perhaps you don't have a git client installed on your system)."

You could also split it into a couple of tests with the specific error messages for each kind of problem detected (a) "not a git working dir" and (b) "git client not available".

**Comment by khaledhosny** [comment]
Users should build from the release tarball, building from git is for developers and the current autogen.sh is good enough for that. Patches are welcome, though.

**Comment by khaledhosny** [comment]
That line checks if `.git` directory is found and if this is true it checks if you have git in PATH.

**Comment by felipesanches** [comment]
One of the FontBakery users (not myself) had trouble setting it up earlier this week.

**Comment by khaledhosny** [comment]
He should be building from release tarball, or even using the provided binaries.
