### ISSUE TITLE
autoreconf not found

### ISSUE THREAD

**Issue by miguelsousa** [khaledhosny/ots#158]
When building the tools on a new Mac using the instructions listed on [INSTALL](https://github.com/khaledhosny/ots/blob/master/INSTALL), I got a `autoreconf not found` error when running `$ ./autogen.sh`. The solution was to install `automake`.

Is this something that should be added to the build instructions?

**Comment by khaledhosny** [comment]
It is implied that `automake` and `autoconf` are needed when building from the repository (as opposed to release tarball), but making it explicit in the build instructions won’t hurt.
