### ISSUE TITLE
OTS weight range ends at 999, however, the spec says it ends at 1000 (OS/2 table)

### ISSUE THREAD

**Issue by kobalicek** [khaledhosny/ots#167]
This is more likely a question than an issue:

What OTS currently does is this:

```c++
if (this->table.weight_class > 999) {
    Warning("Bad usWeightClass: %u, changing it to %d",
             this->table.weight_class, 999);
    this->table.weight_class = 999;
  }
```

However, the spec says that "Values from 1 to 1000 are valid":

  https://docs.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass

I'm just curious why 999 and not 1000 as MS says.

**Comment by khaledhosny** [comment]
See #49, which was based on the old version of the spec.

**Comment by kobalicek** [comment]
Thanks!

I did a bit more digging and it seems that it really should end at 999. I think MS is inconsistent here as they mention 1000 in OpenType and then "Font weight values less than 1 or greater than 999 are considered invalid, and they are rejected by font API functions" in DirectWrite, for example (from https://msdn.microsoft.com/en-us/library/windows/desktop/dd368082(v=vs.85).aspx).

**Comment by khaledhosny** [comment]
Still, OTS is not really a linter, its main goal is to prevent crashes and other nasty things from happening with untrusted fonts.

**Comment by kobalicek** [comment]
I know and it's really cool.

Just as a curiosity, here is stats from 216327 fonts that I use for testing:

```
Weight {
  400: 108907 (50.3%)
  500: 58170 (26.9%)
  700: 30734 (14.2%)
  300: 5758 (2.7%)
  900: 3542 (1.6%)
  550: 2743 (1.3%)
  600: 2199 (1%)
  100: 1856 (0.9%)
  800: 1006 (0.5%)
  250: 247 (0.1%)
  750: 231 (0.1%)
  200: 219 (0.1%)
  275: 152 (0.1%)
  17661: 118 (0.1%)
  1000: 82 (0%)
  850: 73 (0%)
  450: 55 (0%)
  350: 49 (0%)
  950: 43 (0%)
  325: 24 (0%)
  31996: 13 (0%)
  28926: 12 (0%)
  375: 11 (0%)
  3326: 11 (0%)
  650: 10 (0%)
  0: 8 (0%)
  65535: 8 (0%)
  425: 5 (0%)
  575: 4 (0%)
  592: 4 (0%)
  725: 4 (0%)
  475: 3 (0%)
  390: 3 (0%)
  7940: 3 (0%)
  525: 2 (0%)
  675: 2 (0%)
  625: 2 (0%)
  1100: 2 (0%)
  150: 2 (0%)
  260: 1 (0%)
  610: 1 (0%)
  280: 1 (0%)
  10: 1 (0%)
  11010: 1 (0%)
  56: 1 (0%)
  22275: 1 (0%)
  50: 1 (0%)
  40: 1 (0%)
  975: 1 (0%)
}
```
Only minority of fonts are outside the spec, but they definitely exist.
