### ISSUE TITLE
building from source: sanitycheckc.exe

### ISSUE THREAD

**Issue by laerm0** [khaledhosny/ots#174]
Hello -

I am trying to build from source on chromeos (yep, I'm crazy and trying to turn this thing into a font development tool). I am hung up at the part of the build phase that calls an exe (?!?!). I dunno if this is `meson` or a part of `ots`.

```The Meson build system
Version: 0.47.2
Source dir: /home/chronos/user/Downloads/apps/ots
Build dir: /home/chronos/user/Downloads/apps/ots/build
Build type: native build
Project name: ots
Project version: 7.1.7

meson.build:1:0: ERROR:  Could not invoke sanity test executable: [Errno 13] Permission denied: '/home/chronos/user/Downloads/apps/ots/build/meson-private/sanitycheckc.exe'.
```

Any thoughts welcome. Thanks!

**Comment by khaledhosny** [comment]
That error comes from [meson](https://github.com/mesonbuild/meson), apparently it can not execute the file `build/meson-private/sanitycheckc.exe`, apparently not enough permissions. Can you check if you can manually run it?

**Comment by laerm0** [comment]
Hmm, okay. Well I am not the most experienced at these processes, but I think `mono` is the tool that runs `sanitycheckc.exe`, right? (It's an exe, and I suspect it's not `wine`, so...) The error I get from `mono` is

```
chronos@localhost ~/Downloads/apps/ots/build/meson-private $ mono sanitycheckc.exe
Cannot open assembly 'sanitycheckc.exe': File does not contain a valid CIL image.
```

If there's something else I should be doing, please let me know. Thanks!

**Comment by laerm0** [comment]
Hi there, the developers of chromebrew have been helpful in adding it as a package, but I get a [meson error there](https://github.com/skycocker/chromebrew/issues/2642) as well (a different one, though).

**Comment by JL2210** [comment]
Sorry. The home folder in Chrome OS is not mounted as exec by default. This can be closed.

**Comment by JL2210** [comment]
Just because it has an `exe` extension doesn't mean that it's a Windows executable.

**Comment by khaledhosny** [comment]
Closing then.

**Comment by khaledhosny** [comment]
`sanitycheckc.exe` is a native executable, despite the unusual (for Linux at least) file extension.

**Comment by JL2210** [comment]
Correct.
