### ISSUE TITLE
Add CFF2 support

### ISSUE THREAD

**Issue by blueshade7** [khaledhosny/ots#175]
Currently ots-sanitize can't recognize CFF2 fonts.
```
% ots-sanitize AdobeVFPrototype.otf
ERROR: no supported glyph shapes table(s) present
Failed to sanitize file!
```

**Comment by khaledhosny** [comment]
Hmm, good catch. I wonder how Firefox and Chrome are handling this, passing `CFF2` table unsanitized?

**Comment by khaledhosny** [comment]
I’m told that Apple does not support `CFF2` table, so as such not usable on the web, making it a low priority for now.

**Comment by madig** [comment]
Firefox 64 seems to just refuse to load CFF2 VFs.

**Comment by behdad** [comment]
@jfkthame @drott

**Comment by lancejpollard** [comment]
I spent a few days on this, darnit.

**Comment by jfkthame** [comment]
Yeah, Firefox doesn't currently accept CFF2 webfonts; it just hasn't become a priority yet. In particular, without support in macOS, it seems of limited value.

**Comment by drott** [comment]
OTS is not opened up for CFF2 yet in Chromium - but I should do that. We always have FreeType as a fallback backend and choose it when needed.

**Comment by cjchapman** [comment]
I thought that this line would prevent the `ERROR: no supported glyph shapes table(s) present` message for a CFF2 font:
https://github.com/khaledhosny/ots/blob/dc36d4d01591af224572ddf355e5a7fe44840b09/src/ots.cc#L712

...and yet I still see it with OTS 7.1.9:
```bash
cchapman-macOS:OTF cchapman$ ots-sanitize --version
ots 7.1.9
cchapman-macOS:OTF cchapman$ ots-sanitize AdobeBlackVF.otf
WARNING: STAT: Unexpected non-zero offsetToAxisValueOffsets
ERROR: no supported glyph shapes table(s) present
Failed to sanitize file!
```
```python
>>> font = TTFont('AdobeBlackVF.otf')
>>> font.keys()
['GlyphOrder', 'head', 'hhea', 'maxp', 'OS/2', 'hmtx', 'cmap', 'name', 'post', 'BASE', 'CFF2', 'GSUB', 'HVAR', 'STAT', 'VORG', 'VVAR', 'fvar', 'vhea', 'vmtx', 'DSIG']
```

**Comment by khaledhosny** [comment]
That would have effect if either the `CFF2` was sanitized (which OTS does not support yet) or was one of the “passthru” tables (by default we don’t passthru any table, but clients can add tables they are sure don’t need to be sanitized).

**Comment by khaledhosny** [comment]
#193 adds CFF2 support, code review and/or testing is appreciated.
