### ISSUE TITLE
ots-sanitizer 7.1.7 binary is dropping variation tables

### ISSUE THREAD

**Issue by harbortype** [khaledhosny/ots#176]
I tried running the 7.1.7 version on a variable font. I get no warnings, but the `STAT`, `fvar` and `gvar` tables get dropped.

```
henrique-mm:ots-7.1.7-osx henrique$ ./ots-sanitize /Users/henrique/Desktop/temp/RocherTestGX.ttf RocherTestGX-7.1.7.ttf
File sanitized successfully!
```

On the other hand, the 7.0.0 version keeps these tables and gives me a warning.

```
henrique-mm:ots-7.0.0-osx henrique$ ./ots-sanitize /Users/henrique/Desktop/temp/RocherTestGX.ttf RocherTestGX-7.0.0.ttf
WARNING: STAT: Unexpected non-zero offsetToAxisValueOffsets
File sanitized successfully!
```

Is it supposed to work like that? Here are the original and sanitized font files for your reference: [RocherTestGX.zip](https://github.com/khaledhosny/ots/files/2412157/RocherTestGX.zip). 

I've downloaded the pre-compiled binaries from the releases page. I'm on MacOS 10.13.6.

**Comment by khaledhosny** [comment]
You can use 7.0.0 for now. It was a bug in the meson build scripts that is fixed in master.

**Comment by khaledhosny** [comment]
I tagged a new release, binaries should be available shortly.
