### ISSUE TITLE
DEBUG option is not needed in `meson.build`

### ISSUE THREAD

**Issue by devosb** [khaledhosny/ots#177]
When trying to compile the latest sources from git on Ubuntu Bionic I get a message
```
meson.build:12:3: ERROR: Tried to access unknown option "debug".
```
when running the command `meson build` and the build fails. Removing the lines
```
if get_option('debug')
  conf.set('OTS_DEBUG', 1)
endif
```
from the file `meson.build` allows the build to finish.

**Comment by khaledhosny** [comment]
I think you need a newer version of meson or revert this commit https://github.com/khaledhosny/ots/commit/955be403ba7fc6b6c237f8680668302d3ff262a5. I don’t know how to conditionally handle this based on meson version.

**Comment by devosb** [comment]
You are correct, I upgraded to the latest git sources for meson, and ots built. Thanks for the tip.
