### ISSUE TITLE
ERROR: GDEF: bad caret value format: 3

### ISSUE THREAD

**Issue by thundernixon** [khaledhosny/ots#178]
I'm currently doing production work on a couple of variable fonts. My workflow is exporting from GlyphsApp sources to VFs, with FontMake, then checking with FontBakery.

As a concrete example, my repo of [Encode Sans](https://github.com/thundernixon/Encode-Sans) can be built by running the shell script `scripts/build.sh` in a Python3 environment with Google Fonts tools installed. As a faster example, you can view [the most recent build, TTX, and FontBakery report](https://github.com/thundernixon/Encode-Sans/tree/d1c1634c1a362187ab376011a28f28b730697c39/dist/EncodeSans-VF-2018-11-23-13_12).

I am getting the following error from OTS which I don't think is valid:

> ERROR: GDEF: bad caret value format: 3
> ERROR: GDEF: Invalid ligature caret list
> ERROR: GDEF: Failed to parse table
> Failed to sanitize file!

On line 170 of [ots/src/gdef.cc](https://github.com/khaledhosny/ots/blob/63f8d7e47cf9ab75a25b2b63bb359349fef050fa/src/gdef.cc), there is the following comment:

>       // TODO(bashi): We only support caret value format 1 and 2 for now
>       // because there are no fonts which contain caret value format 3
>       // as far as we investigated.

However, in the TTX of my variable font, I have `<CaretValue index="0" Format="3">` for each caret description in the `<LigCaretList>` table. This is also the case in [my latest Libre Caslon build](https://github.com/thundernixon/Libre-Caslon/tree/6dec2ae7747012cffd2d47aba5167c042b93e630/dist/2018-11-23-15_05).

On [MS Docs for the GDEF table](https://docs.microsoft.com/en-us/typography/opentype/otspec140/gdef#ligature-caret-list-table), it says:

> One format represents values in design units only, another fine-tunes a value based on a designated contour point, and the third uses a Device table to adjust values at specific font sizes.

I am simply following the GlyphsApp recommendation for inserting caret positions, as described on page 27 of the [Glyphs Handbook](https://glyphsapp.com/downloads/handbook/Glyphs-Handbook-2.3.pdf) - inserting an anchor labeled `caret_1`. So, I'm guessing that if my exported variable font is getting `format 3` from either GlyphsApp or from FontMake's VF exporting.

In any case, it doesn't seem to be an actual error, from what I can tell, so it may be something worth updating in OTS.

If I am wrong or if this seems to instead be a problem in the FontMake/FontTools chain, please let me know! Otherwise, this might be something to re-evaluate if `format="3"` carets are the usual for variable fonts.

**Comment by khaledhosny** [comment]
Can you attach the built font? It might also be a fontmake/glyphlib issue if the font they generate uses a different format than what Glyphs does. Even if OTS was fixed today, it will take months or even more for that fix to reach the users of stable browser releases.

**Comment by behdad** [comment]
There's only one format (32768) for variable Device tables.

**Comment by davelab6** [comment]
Font attached from https://github.com/thundernixon/Encode-Sans/blob/9c21a54fa89e384b9cfe97bb254e26a0e4df531e/dist/EncodeSans-VF-2018-11-24-22_01/EncodeSans-VF.ttf

[EncodeSans-VF.ttf.zip](https://github.com/khaledhosny/ots/files/2621256/EncodeSans-VF.ttf.zip)

**Comment by khaledhosny** [comment]
Thanks for the font. In the meantime you can drop ligature carets, no browser is using it anyway.

**Comment by thundernixon** [comment]
Thanks for adding my font, Dave!

I think I'll just leave ligature carets in the font for software that does support them, and ignore the warning from OTF sanitize for now.

**Comment by mjlagattuta** [comment]
@khaledhosny if you need additional fonts using this CaretValue format, here is another: https://github.com/googlefonts/robotoslab/tree/master/fonts/variable

**Comment by khaledhosny** [comment]
Thanks for the fonts. I’m a bit busy right now, but if someone can come up with a pull request I’ll try to review and merge it.

**Comment by thundernixon** [comment]
As a small update in case others come across this: 

I hadn't quite understood the advice given to "drop ligature carets" (even though it's pretty clear), until I heard it restated as "remove ligature carets." I also hadn't quite understood that this wouldn't work in Firefox until OTS passed. So, I'll remove the ligature carets, and consider adding them into fonts in a few months. 

Thanks again for the help here!

**Comment by khaledhosny** [comment]
Fixed in #182.
