### ISSUE TITLE
Validate TrueType bytecode and Type 1 fonts

### ISSUE THREAD

**Issue by DemiMarie** [khaledhosny/ots#179]
I suspect there are some vulnerabilities in the handling of these fonts by some software.  OTS should validate the bytecode.

**Comment by khaledhosny** [comment]
I don’t think Type 1 fonts are supported on the web (not as webfonts at least, which what OTS is concerned about). Please open more specific issues about TrueType bytecode (though I don’t think static validation of it is feasible).
