### ISSUE TITLE
STAT table false warn: “nameID out of range”

### ISSUE THREAD

**Issue by mjlagattuta** [khaledhosny/ots#180]
When running ots-sanitize from fontbakery to check [Cabin](https://github.com/mjlagattuta/Cabin/tree/master/fonts/VF-final) VF, I was getting the following warning:
```
>> com.google.fonts/check/036 with (('font[0]', 'VF-final/Cabin-VF.ttf'),)
   Checking with ots-sanitize.
 * WARN: ots-sanitize passed this file, however warnings were printed:

WARNING: STAT: Axis value nameID out of range


   Result: WARN
```

<br>

I verified that all nameIDs used in the STAT table are also in the name table and then dug into the code  and found the root of the issue. One of my nameIDs is nameID 2 which is considered out of range by the following code from https://github.com/khaledhosny/ots/blob/master/src/stat.cc:

```C
if (axisValue.format3.valueNameID <= 255 || axisValue.format3.valueNameID >= 32768) {
        Warning("Axis value nameID out of range");
```

<br>

After double checking the [ot spec](https://docs.microsoft.com/en-us/typography/opentype/spec/stat) I believe this should be modified. For axis names, the above code is in line with the spec:
> The axisNameID field provides a name ID that can be used to obtain strings from the 'name' table that can be used to refer to the axis in application user interfaces. The name ID must be greater than 255 and less than 32768.

<br>

But for axis value nameIDs, the spec has the following guidance:
> Each format includes a valueNameID field, which references a display string to be associated with the numeric axis value or combination of axis values. Defined name IDs, such as name IDs 2, 17 or 22, can be used if those have the appropriate string for an axis value. Otherwise, name IDs must be greater than 255 and less than 32768.

**Comment by khaledhosny** [comment]
Sounds right, please send a PR (preferably also adding a test font).

**Comment by davelab6** [comment]
Sadly @mjlagattuta isn't experienced with C programming so a PR from him  seems unlikely :) I hope @rsheeter can help with this in January. 

Test font is https://github.com/mjlagattuta/Cabin/blob/f6391dd5d602ec3cecdcf2b1cc442627cf009ce7/fonts/VF-final/Cabin-Roman-VF.ttf

**Comment by mjlagattuta** [comment]
Thanks @davelab6  for adding the test font!

Yes I would be hesitant to contribute any C code to anything at the moment,  though this seems like a simple fix since the valid name IDs are the same across all 4 formats of axisValue entries, potentially:
```C

if (axisValue.format3.valueNameID <= 255 &&
    axisValue.format3.valueNameID != 2 && 
    axisValue.format3.valueNameID != 17 && 
    axisValue.format3.valueNameID != 22){
  Warning("Axis value nameID out of range");
} else if (axisValue.format3.valueNameID >= 32768){
  Warning("Axis value nameID out of range");
}
```
