### ISSUE TITLE
ahronbd.ttf fails validation

### ISSUE THREAD

**Issue by eaenet** [khaledhosny/ots#181]
Originally filed as chromium issue, crbug.com/920708

OTS fails to parse the glyf table in ahronbd.ttf even though most other software handle it correctly.
"glyf: Failed to parse table"

[ahronbd.ttf.gz](https://github.com/khaledhosny/ots/files/2747514/ahronbd.ttf.gz)

**Comment by khaledhosny** [comment]
```
$ ./ots-sanitize ahronbd.ttf 
ERROR: glyf: Bytecode length is bigger than maxp.maxSizeOfInstructions 167: 171
ERROR: glyf: Failed to parse glyph 118
ERROR at ../src/ots.cc:698 (ProcessGeneric)
ERROR: glyf: Failed to parse table
Failed to sanitize file!
```

So looks like the font has some bad hinting bytecode.

**Comment by behdad** [comment]
Sure font had bad value in maxp. But that's not a good reason to fail the font. Again, linter vs security guard debate of what ots actually is for...

**Comment by khaledhosny** [comment]
I’m checking it and looks like a useless check indeed.

**Comment by eaenet** [comment]
Thanks for the analysis and for considering relaxing the checks. Is there anything I can do to help?

**Comment by khaledhosny** [comment]
We either want to relax the check or update the maxp.maxSizeOfInstructions with whatever value we think it correct. I appreciate if you can help with checking which of these makes more sense/is feasible, otherwise I’ll get around checking eventually.

**Comment by khaledhosny** [comment]
> Does ots have a concept of warning vs error? That would be convenient for cases like this. Ots can also fix that number in maxp...

We have warnings, so that is another option if fixing is not practical.
