### ISSUE TITLE
If CFF and/or CFF2 work

### ISSUE THREAD

**Issue by lancejpollard** [khaledhosny/ots#183]
I am trying to get CFF2 working but after a few days it seems that it might not be supported by Chrome.

http://typedrawers.com/discussion/3029/whats-wrong-with-this-cff2-data#latest

Wondering if CFF2 is implemented yet, and if so if it is working. If not then that's why I'm not able to get it to work.

Also would like to know if CFF (CFF 1 I guess) is working and supported by all major browsers / platforms. Or if TTF is the only one widely supported.

Thank you.

**Comment by khaledhosny** [comment]
OTS does not yet support `CFF2` table see #175 , `CFF ` table is supported.
