### ISSUE TITLE
ERROR: CFF : Failed validating charstring set 0

### ISSUE THREAD

**Issue by lancejpollard** [khaledhosny/ots#184]
Getting this from `fontbakery`:

    >> com.google.fonts/check/036 with (('font[0]', 'Regular.otf'),)
       Checking with ots-sanitize.
     * FAIL: ots-sanitize returned an error code (1). Output follows:

    ERROR: CFF : Failed validating charstring set 0
    ERROR: CFF : Failed to parse table
    Failed to sanitize file!

Even though it seems CFF is fine:

    $ spot -t CFF Regular.otf
    ### [CFF_] (0000009c)
    FontName    =<Foo>
    version     =<0.0.0>
    Notice      =<asdfasdf>
    Copyright   =<foobarbaz>
    FamilyName  =<Foo>
    FullName    =<Foo Regular>
    FontBBox    =[0 0 1364 682]
    unitsPerEm  =2048
    isFixedPitch=0
    ItalicAngle =0.000 (00000000)
    UnderlinePosition =-100
    UnderlineThickness=50
    Encoding    =0
    charset     =3
    nGlyphs     =7

Then here is TTX:

    <?xml version="1.0" encoding="UTF-8"?>
    <ttFont sfntVersion="OTTO" ttLibVersion="3.35">

    <GlyphOrder>
      
      <GlyphID id="0" name=".notdef"/>
      <GlyphID id="1" name="b"/>
      <GlyphID id="2" name="d"/>
      <GlyphID id="3" name="e"/>
      <GlyphID id="4" name="f"/>
      <GlyphID id="5" name="g"/>
      <GlyphID id="6" name="h"/>
    </GlyphOrder>

    <head>
      
      <tableVersion value="1.0"/>
      <fontRevision value="1.0681"/>
      <checkSumAdjustment value="0x0"/>
      <magicNumber value="0x5f0f3cf5"/>
      <flags value="00000000 00000011"/>
      <unitsPerEm value="2048"/>
      <created value="Thu Jan 31 11:31:31 2019"/>
      <modified value="Thu Jan 31 11:31:31 2019"/>
      <xMin value="0"/>
      <yMin value="0"/>
      <xMax value="1000"/>
      <yMax value="2800"/>
      <macStyle value="00000000 00000000"/>
      <lowestRecPPEM value="9"/>
      <fontDirectionHint value="2"/>
      <indexToLocFormat value="1"/>
      <glyphDataFormat value="0"/>
    </head>

    <hhea>
      <tableVersion value="0x00010000"/>
      <ascent value="1364"/>
      <descent value="682"/>
      <lineGap value="0"/>
      <advanceWidthMax value="682"/>
      <minLeftSideBearing value="0"/>
      <minRightSideBearing value="0"/>
      <xMaxExtent value="0"/>
      <caretSlopeRise value="1"/>
      <caretSlopeRun value="0"/>
      <caretOffset value="0"/>
      <reserved0 value="0"/>
      <reserved1 value="0"/>
      <reserved2 value="0"/>
      <reserved3 value="0"/>
      <metricDataFormat value="0"/>
      <numberOfHMetrics value="7"/>
    </hhea>

    <maxp>
      
      <tableVersion value="0x10000"/>
      <numGlyphs value="7"/>
      <maxPoints value="18"/>
      <maxContours value="3"/>
      <maxCompositePoints value="0"/>
      <maxCompositeContours value="0"/>
      <maxZones value="1"/>
      <maxTwilightPoints value="0"/>
      <maxStorage value="0"/>
      <maxFunctionDefs value="0"/>
      <maxInstructionDefs value="0"/>
      <maxStackElements value="0"/>
      <maxSizeOfInstructions value="0"/>
      <maxComponentElements value="0"/>
      <maxComponentDepth value="0"/>
    </maxp>

    <OS_2>
      
      <version value="5"/>
      <xAvgCharWidth value="682"/>
      <usWeightClass value="500"/>
      <usWidthClass value="5"/>
      <fsType value="00000000 00000000"/>
      <ySubscriptXSize value="650"/>
      <ySubscriptYSize value="699"/>
      <ySubscriptXOffset value="0"/>
      <ySubscriptYOffset value="140"/>
      <ySuperscriptXSize value="650"/>
      <ySuperscriptYSize value="699"/>
      <ySuperscriptXOffset value="0"/>
      <ySuperscriptYOffset value="479"/>
      <yStrikeoutSize value="49"/>
      <yStrikeoutPosition value="258"/>
      <sFamilyClass value="0"/>
      <panose>
        <bFamilyType value="0"/>
        <bSerifStyle value="0"/>
        <bWeight value="0"/>
        <bProportion value="9"/>
        <bContrast value="0"/>
        <bStrokeVariation value="0"/>
        <bArmStyle value="0"/>
        <bLetterForm value="0"/>
        <bMidline value="0"/>
        <bXHeight value="0"/>
      </panose>
      <ulUnicodeRange1 value="00000000 00000000 00000000 00000000"/>
      <ulUnicodeRange2 value="00000000 00000000 00000000 00000000"/>
      <ulUnicodeRange3 value="00000000 00000000 00000000 00000000"/>
      <ulUnicodeRange4 value="00000000 00000000 00000000 00000000"/>
      <achVendID value="XXXX"/>
      <fsSelection value="00000000 01000000"/>
      <usFirstCharIndex value="97"/>
      <usLastCharIndex value="104"/>
      <sTypoAscender value="1364"/>
      <sTypoDescender value="682"/>
      <sTypoLineGap value="0"/>
      <usWinAscent value="2800"/>
      <usWinDescent value="0"/>
      <ulCodePageRange1 value="00000000 00000000 00000000 00000001"/>
      <ulCodePageRange2 value="00000000 00000000 00000000 00000000"/>
      <sxHeight value="682"/>
      <sCapHeight value="40"/>
      <usDefaultChar value="0"/>
      <usBreakChar value="0"/>
      <usMaxContext value="0"/>
      <usLowerOpticalPointSize value="0.0"/>
      <usUpperOpticalPointSize value="0.15"/>
    </OS_2>

    <name>
      <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
        Foo
      </namerecord>
      <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
        Regular
      </namerecord>
      <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
        foo
      </namerecord>
      <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0" unicode="True">
        Foo Regular
      </namerecord>
      <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
        Version 1.000
      </namerecord>
      <namerecord nameID="6" platformID="1" platEncID="0" langID="0x0" unicode="True">
        Foo
      </namerecord>
      <namerecord nameID="13" platformID="1" platEncID="0" langID="0x0" unicode="True">
        Licensed under the Apache License, Version 2.0
      </namerecord>
    </name>

    <cmap>
      <tableVersion version="0"/>
      <cmap_format_4 platformID="3" platEncID="1" language="0">
        <map code="0x62" name="b"/>
        <map code="0x64" name="d"/>
        <map code="0x65" name="e"/>
        <map code="0x66" name="f"/>
        <map code="0x67" name="g"/>
        <map code="0x68" name="h"/>
      </cmap_format_4>
    </cmap>

    <post>
      <formatType value="3.0"/>
      <italicAngle value="0.0"/>
      <underlinePosition value="0"/>
      <underlineThickness value="0"/>
      <isFixedPitch value="1"/>
      <minMemType42 value="0"/>
      <maxMemType42 value="0"/>
      <minMemType1 value="0"/>
      <maxMemType1 value="0"/>
    </post>

    <CFF>
      <major value="1"/>
      <minor value="0"/>
      <CFFFont name="Foo">
        <version value="0.0.0"/>
        <Notice value="asdfasdf"/>
        <Copyright value="foobarbaz"/>
        <FullName value="Foo Regular"/>
        <FamilyName value="Foo"/>
        <Weight value="Regular"/>
        <isFixedPitch value="0"/>
        <ItalicAngle value="0"/>
        <UnderlinePosition value="-100"/>
        <UnderlineThickness value="50"/>
        <PaintType value="0"/>
        <CharstringType value="2"/>
        <FontMatrix value="0.00048828125 0.0 0.0 0.00048828125 0.0 0.0"/>
        <FontBBox value="0 0 1364 682"/>
        <StrokeWidth value="0"/>
        
        <Encoding name="StandardEncoding"/>
        <Private>
          <BlueValues value="0 0"/>
          <BlueScale value="0.039625"/>
          <BlueShift value="7"/>
          <BlueFuzz value="1"/>
          <ForceBold value="0"/>
          <LanguageGroup value="0"/>
          <ExpansionFactor value="0.06"/>
          <initialRandomSeed value="0"/>
          <defaultWidthX value="0"/>
          <nominalWidthX value="0"/>
        </Private>
        <CharStrings>
          <CharString name=".notdef">
            682 100 100 rlineto
            500 0 rmoveto
            0 1900 rmoveto
            -500 0 rmoveto
            0 -1900 rmoveto
            endchar
          </CharString>
          <CharString name="b">
            682 0 1364 rlineto
            20 0 rmoveto
            0 -682 rmoveto
            180 0 rmoveto
            -200 -682 rmoveto
            0 1364 rmoveto
            20 662 rlineto
            160 0 rmoveto
            -160 -642 rmoveto
            0 642 rmoveto
            endchar
          </CharString>
          <CharString name="d">
            682 900 200 rlineto
            0 1800 rmoveto
            900 1000 rlineto
            -300 0 rmoveto
            300 1000 rmoveto
            endchar
          </CharString>
          <CharString name="e">
            682 900 1000 rlineto
            -300 0 rmoveto
            300 1000 rmoveto
            1000 1500 rlineto
            -200 0 rmoveto
            endchar
          </CharString>
          <CharString name="f">
            682 900 1000 rlineto
            -300 0 rmoveto
            -500 1000 rmoveto
            100 1500 rlineto
            700 0 rmoveto
            endchar
          </CharString>
          <CharString name="g">
            682 900 1000 rlineto
            -300 0 rmoveto
            300 1000 rmoveto
            900 1500 rlineto
            -400 0 rmoveto
            900 1500 rlineto
            0 1300 rmoveto
            endchar
          </CharString>
          <CharString name="h">
            682 100 200 rlineto
            0 1800 rmoveto
            100 1500 rlineto
            800 0 rmoveto
            900 1000 rlineto
            0 1000 rmoveto
            endchar
          </CharString>
        </CharStrings>
      </CFFFont>

      <GlobalSubrs>
        
      </GlobalSubrs>
    </CFF>

    <hmtx>
      <mtx name=".notdef" width="682" lsb="100"/>
      <mtx name="b" width="682" lsb="100"/>
      <mtx name="d" width="682" lsb="100"/>
      <mtx name="e" width="682" lsb="100"/>
      <mtx name="f" width="682" lsb="100"/>
      <mtx name="g" width="682" lsb="100"/>
      <mtx name="h" width="682" lsb="100"/>
    </hmtx>

    </ttFont>

Wondering if anyone knows what perhaps can be wrong with this. The full font file is this:

    $ xxd Regular.otf
    00000000: 4f54 544f 0009 0080 0003 0010 4346 4620  OTTO........CFF
    00000010: 0000 0000 0000 009c 0000 01a0 4f53 2f32  ............OS/2
    00000020: 0000 0000 0000 023c 0000 0064 636d 6170  .......<...dcmap
    00000030: 0000 0000 0000 02a0 0000 006c 6865 6164  ...........lhead
    00000040: 0000 0000 0000 030c 0000 0036 6868 6561  ...........6hhea
    00000050: 0000 0000 0000 0344 0000 0024 686d 7478  .......D...$hmtx
    00000060: 0000 0000 0000 0368 0000 001c 6d61 7870  .......h....maxp
    00000070: 0000 0000 0000 0384 0000 0020 6e61 6d65  ........... name
    00000080: 0000 0000 0000 03a4 0000 00ad 706f 7374  ............post
    00000090: 0000 0000 0000 0454 0000 0020 0100 0401  .......T... ....
    000000a0: 0001 0101 0446 6f6f 0001 0101 58f8 1b00  .....Foo....X...
    000000b0: f81c 01f8 1d0c 00f8 1e02 f81f 03f8 2004  .............. .
    000000c0: 8b0c 018b 0c02 8d0c 061e 0a00 0488 2812  ..............(.
    000000d0: 5f1e 0f1e 0f1e 0a00 0488 2812 5f1e 0f1e  _.........(._...
    000000e0: 0f0c 078b 8b1c 0554 f93e 051d 0000 00ab  .......T.>......
    000000f0: 0f1d 0000 0000 101d 0000 00b8 118e 1d00  ................
    00000100: 0001 9d12 000c 0101 060e 1722 252c 2d2e  ..........."%,-.
    00000110: 2f30 3132 302e 302e 3061 7364 6661 7364  /0120.0.0asdfasd
    00000120: 6666 6f6f 6261 7262 617a 466f 6f20 5265  ffoobarbazFoo Re
    00000130: 6775 6c61 7246 6f6f 5265 6775 6c61 7262  gularFooRegularb
    00000140: 6465 6667 6800 0000 018d 018e 018f 0190  defgh...........
    00000150: 0191 0192 0007 0101 1947 627d 97bd dbf9  .........Gb}....
    00000160: 3eef ef05 f888 8b15 8b1c 076c 15fc 888b  >..........l....
    00000170: 158b 1cf8 9415 0ef9 3e8b 1c05 5405 9f8b  ........>...T...
    00000180: 158b fd3e 15f7 488b 15fb 5cfd 3e15 8b1c  ...>..H...\.>...
    00000190: 0554 159f f92a 05f7 348b 15fb 34fd 1615  .T...*..4...4...
    000001a0: 8bf9 1615 0ef9 3efa 18f7 5c05 8b1c 0708  ......>...\.....
    000001b0: 15fa 18fa 7c05 fbc0 8b15 f7c0 fa7c 150e  ....|........|..
    000001c0: f93e fa18 fa7c 05fb c08b 15f7 c0fa 7c15  .>...|........|.
    000001d0: fa7c 1c05 dc05 fb5c 8b15 0ef9 3efa 18fa  .|.....\....>...
    000001e0: 7c05 fbc0 8b15 fc88 fa7c 15ef 1c05 dc05  |........|......
    000001f0: f950 8b15 0ef9 3efa 18fa 7c05 fbc0 8b15  .P....>...|.....
    00000200: f7c0 fa7c 15fa 181c 05dc 05fc 248b 15fa  ...|........$...
    00000210: 181c 05dc 058b 1c05 1415 0ef9 3eef f75c  ............>..\
    00000220: 058b 1c07 0815 ef1c 05dc 05f9 b48b 15fa  ................
    00000230: 18fa 7c05 8bfa 7c15 0e8b 8b06 0005 02aa  ..|...|.........
    00000240: 01f4 0005 0000 028a 02bb 0000 008c 028a  ................
    00000250: 02bb 0000 01df 0031 0102 0000 0000 0009  .......1........
    00000260: 0000 0000 0000 0000 0000 0000 0000 0000  ................
    00000270: 0000 0000 0000 5858 5858 0040 0061 0068  ......XXXX.@.a.h
    00000280: 0554 02aa 0000 0af0 0000 0000 0001 0000  .T..............
    00000290: 0000 02aa 0028 0000 0000 0000 0000 0003  .....(..........
    000002a0: 0000 0001 0003 0001 0000 000c 0004 0060  ...............`
    000002b0: 0000 0010 0010 0003 0000 0061 0062 0064  ...........a.b.d
    000002c0: 0065 0066 0067 0068 ffff 0000 0061 0062  .e.f.g.h.....a.b
    000002d0: 0064 0065 0066 0067 0068 ffff ff9f ff9f  .d.e.f.g.h......
    000002e0: ff9e ff9e ff9e ff9e ff9e 0001 0000 0000  ................
    000002f0: 0000 0000 0000 0000 0000 0000 0000 0001  ................
    00000300: 0002 0003 0004 0005 0006 0000 0001 0000  ................
    00000310: 0001 116f 0000 0000 5f0f 3cf5 0003 0800  ...o...._.<.....
    00000320: 0000 0000 d878 8d13 0000 0000 d878 8d13  .....x.......x..
    00000330: 0000 0000 03e8 0af0 0000 0009 0002 0001  ................
    00000340: 0000 0000 0001 0000 0554 02aa 0000 02aa  .........T......
    00000350: 0000 0000 0000 0001 0000 0000 0000 0000  ................
    00000360: 0000 0000 0000 0007 02aa 0064 02aa 0064  ...........d...d
    00000370: 02aa 0064 02aa 0064 02aa 0064 02aa 0064  ...d...d...d...d
    00000380: 02aa 0064 0001 0000 0007 0012 0003 0000  ...d............
    00000390: 0000 0001 0000 0000 0000 0000 0000 0000  ................
    000003a0: 0000 0000 0000 0007 005a 0001 0000 0000  .........Z......
    000003b0: 0001 0003 0000 0001 0000 0000 0002 0007  ................
    000003c0: 0003 0001 0000 0000 0003 0003 000a 0001  ................
    000003d0: 0000 0000 0004 000b 000d 0001 0000 0000  ................
    000003e0: 0005 000d 0046 0001 0000 0000 0006 0003  .....F..........
    000003f0: 0000 0001 0000 0000 000d 002e 0018 466f  ..............Fo
    00000400: 6f52 6567 756c 6172 666f 6f46 6f6f 2052  oRegularfooFoo R
    00000410: 6567 756c 6172 4c69 6365 6e73 6564 2075  egularLicensed u
    00000420: 6e64 6572 2074 6865 2041 7061 6368 6520  nder the Apache
    00000430: 4c69 6365 6e73 652c 2056 6572 7369 6f6e  License, Version
    00000440: 2032 2e30 5665 7273 696f 6e20 312e 3030   2.0Version 1.00
    00000450: 3000 0000 0003 0000 0000 0000 0000 0000  0...............
    00000460: 0000 0001 0000 0000 0000 0000 0000 0000  ................
    00000470: 0000 0000                                ....

**Comment by khaledhosny** [comment]
Please attach the actual font binary, the TTX file you posted does not compile for me:
```
Compiling "a.ttx" to "a.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'hmtx' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/python3.7/site-packages/fontTools/ttx.py", line 398, in main
    process(jobs, options)
  File "/python3.7/site-packages/fontTools/ttx.py", line 372, in process
    action(input, output, options)
  File "/python3.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/python3.7/site-packages/fontTools/ttx.py", line 290, in ttCompile
    ttf.save(output)
  File "/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 629, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/python3.7/site-packages/fontTools/ttLib/tables/C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "/python3.7/site-packages/fontTools/cffLib/__init__.py", line 108, in compile
    topDict.recalcFontBBox()
  File "/python3.7/site-packages/fontTools/cffLib/__init__.py", line 2344, in recalcFontBBox
    bounds = charString.calcBounds(self.CharStrings)
  File "/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 967, in calcBounds
    self.draw(boundsPen)
  File "/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 962, in draw
    extractor.execute(self)
  File "/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 289, in execute
    rv = handler(index)
  File "/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 580, in op_rlineto
    self.rLineTo(point)
  File "/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 514, in rLineTo
    self.pen.lineTo(self._nextPoint(point))
  File "/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 503, in _nextPoint
    point = x + point[0], y + point[1]
IndexError: list index out of range
```

**Comment by khaledhosny** [comment]
Assuming the font is broken.

**Comment by lancejpollard** [comment]
[Regular.otf.zip](https://github.com/khaledhosny/ots/files/2830811/Regular.otf.zip)

Here is the latest rendition.

**Comment by khaledhosny** [comment]
The file is still broken, no font editor I have ca open it and show any glyphs. Trying to compile back the generated ttx files give the same errors above. Looks like your CharStrings are badly constructed and some operators use the wrong number of arguments. Please make sure the font actually works.

**Comment by lancejpollard** [comment]
That's the issue I'm trying to make sure the font works but it's difficult to debug. Maybe you have some suggestions on debug workflow.

**Comment by lancejpollard** [comment]
Wondering if you can tell from the ttx what's wrong with the CharStrings.


```xml
<CharStrings>
  <CharString name=".notdef">
    682 100 100 rlineto
    500 0 rmoveto
    0 1900 rmoveto
    -500 0 rmoveto
    0 -1900 rmoveto
    endchar
  </CharString>
  <CharString name="b">
    682 0 1364 rlineto
    20 0 rmoveto
    0 -682 rmoveto
    180 0 rmoveto
    -200 -682 rmoveto
    0 1364 rmoveto
    20 662 rlineto
    160 0 rmoveto
    -160 -642 rmoveto
    0 642 rmoveto
    endchar
  </CharString>
  <CharString name="d">
    682 900 200 rlineto
    0 1800 rmoveto
    900 1000 rlineto
    -300 0 rmoveto
    300 1000 rmoveto
    endchar
  </CharString>
  <CharString name="e">
    682 900 1000 rlineto
    -300 0 rmoveto
    300 1000 rmoveto
    1000 1500 rlineto
    -200 0 rmoveto
    endchar
  </CharString>
  <CharString name="f">
    682 900 1000 rlineto
    -300 0 rmoveto
    -500 1000 rmoveto
    100 1500 rlineto
    700 0 rmoveto
    endchar
  </CharString>
  <CharString name="g">
    682 900 1000 rlineto
    -300 0 rmoveto
    300 1000 rmoveto
    900 1500 rlineto
    -400 0 rmoveto
    900 1500 rlineto
    0 1300 rmoveto
    endchar
  </CharString>
  <CharString name="h">
    682 100 200 rlineto
    0 1800 rmoveto
    100 1500 rlineto
    800 0 rmoveto
    900 1000 rlineto
    0 1000 rmoveto
    endchar
  </CharString>
</CharStrings>
```

They look fine to me at first glance without knowing a lot about the syntax.
