### ISSUE TITLE
The font tables that are typically exported by font editors

### ISSUE THREAD

**Issue by lancejpollard** [khaledhosny/ots#185]
I am new to fonts and have built a TrueType font (the start of one) from scratch following the spec. I am not sure what font editors there are or how people typically build fonts, but I am interested to know what they typically export. Specifically, what tables they typically use.

Given that CFF2 currently is not supported by OTS, and Chrome seems to use OTS for font support, this means that font editors probably don't export a CFF2 compatible font. It seems there are only two other choices from my knowledge:

- TTF with glyf and loca tables.
- OTF with CFF_ table (CFF 1 so to speak).

I see opentype.js sort of supports CFF1 and TTF, and TTF is older than OTF.

But given all of this I am not sure what you should be expecting from a font builder/editor. If it should be returning _both_ CFF_ and TTF fonts, or something else. Would be helpful to clarify this as it was difficult figuring out what spec to follow and only later did I realize that OTS was key to implementation detail.

**Comment by khaledhosny** [comment]
I don’t think here is the best place to get answers for these kinds of questions. You might have better luck in OpenType mailing list or some other font discussion forum.

**Comment by Jolg42** [comment]
@lancejpollard Try to drop a few fonts on https://wakamaifondue.com/ to see what's in there. If you want to go deeper I'll suggest fonttools (and [more here](https://github.com/Jolg42/awesome-typography))
