### ISSUE TITLE
Consider add checks for desktop fonts

### ISSUE THREAD

**Issue by be5invis** [khaledhosny/ots#189]
OTS is a great tool for validating fonts for web uses, however there are more weirdnesses for desktop font installation, including:

 - [Win32] Font family name length must < 32 (because [LOGFONTW](https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/ns-wingdi-logfontw)'s name field has only 32 characters).
 - [Win32] GDI will use `xAvgCharWidth` for monospace fonts, and completely ignoring glyphs' advance width.
 - [Mso] Style linking consistency check. Perhaps a multi-font conflict check?
 - [InDesign] InDesign thinks Book and Regular are the same, except for fonts in a hard-coded list.

**Comment by khaledhosny** [comment]
I don’t personally have the capacity to work on this (or the interest, I only got involved with OTS to stop Chrome and Firefox from rejecting my valid fonts, and I’d be more than happy if both managed to do without it entirely). Anyone is free to send pull requests, of course.
