### ISSUE TITLE
changelog/versioning

### ISSUE THREAD

**Issue by Pomax** [khaledhosny/ots#19]
I don't know what the release cycle idea is for the new repo, but it might be a good idea to add a changelog, or tag versioning, to make it easier for people who are mostly interested in using it as a tool "as is" to track "has OTS changed since last I looked at it and should I update my copy"

**Comment by khaledhosny** [comment]
We are tagging releases now, and git log should provide all changelog needed.

**Comment by Pomax** [comment]
awesome!
