### ISSUE TITLE
Graphite tables reserved fields do not have to be 0

### ISSUE THREAD

**Issue by mhosken** [khaledhosny/ots#196]
There are a few fields in the Silf table, particularly that OTS requires to be 0 if the Silf table version is not at least the version that the doc says the field has value and is not simply reserved. This is causing problems because:

1. The specification isn't entirely correct and those values can be used for Silf table versions earlier than they were introduced.
2. There is nothing that says reserved values must be 0.

Please can we relax this requirement in silf.cc. I realise it's only a warning, thankfully, but it would still be nice to not warn on what a valid fonts.

**Comment by khaledhosny** [comment]
The Graphite code has been contributed (and AFAIK only used) by Mozilla and I’m not familiar either with the code or the Graphite spec.

**Comment by khaledhosny** [comment]
Fixed in #198
