### ISSUE TITLE
Support sanitizing COLR and CPAL

### ISSUE THREAD

**Issue by svgeesus** [khaledhosny/ots#202]
Because OTS [does not support COLR or CPAL](https://github.com/khaledhosny/ots/blob/master/docs/DesignDoc.md) then those tables are dropped by OTS. It would therefore be a useful enhancement to support those, so that color fonts can be used safely.

 - [COLR](https://docs.microsoft.com/en-us/typography/opentype/spec/colr)
 - [CPAL](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal)

**Comment by khaledhosny** [comment]
While this would be nice, I don’t think lack of support in OTS is blocking the use of these tables on the web. Both Firefox and Chrome support use of these tables in web fonts e.g. check this page in either browser https://www.amirifont.org/fatiha-colored.html, which suggests they bypass OTS for these tables, so support in OTS wouldn't change much in bractice.

**Comment by svgeesus** [comment]
@khaledhosny thanks for the quick response! I agree that they are bypassing OTS for those tables, so on the one hand the color fonts still work (non-blocking) but on the other hand any problems in the TrueType outlines in COLR will not be caught (sub-optimal).

I wasn't trying to blame OTS for the at-risk status, just filing this while I remembered.

**Comment by jfkthame** [comment]
This was just implemented in https://github.com/khaledhosny/ots/pull/247.
