### ISSUE TITLE
Windows 64 bit package does not contain ots-sanitize.exe

### ISSUE THREAD

**Issue by madig** [khaledhosny/ots#204]
The 32 bit package does, though.

Also, https://pypi.org/project/opentype-sanitizer/#files says the 64 bit package is 287 KB, but downloading the file gives me a 5 KB file???

**Comment by khaledhosny** [comment]
What was the issue, incomplete download?

**Comment by anthrotype** [comment]
I believe too picky antivirus

**Comment by madig** [comment]
We haven't found the cause yet but I also suspect antivirus interference. Downloading with curl says 280 KB, but then the file is missing the exe. This _has_ to be something on our PCs...

**Comment by khaledhosny** [comment]
FWIW, I downloaded the wheel and the zip file in GitHub releases and both have`ots-sanitize.exe`.

**Comment by madig** [comment]
We tracked it down to an overzealous antivirus program, but not before it wiped all instances of ots-*.exe from my disk.
