### ISSUE TITLE
OpenTypeFVAR can be accessed while unitialized

### ISSUE THREAD

**Issue by garretrieger** [khaledhosny/ots#205]
If parsing of fvar fails DropVariations() is called, but the table is retained in the m_tables map since DropVariations() returns true (https://github.com/khaledhosny/ots/blob/master/src/fvar.cc#L23). Later on CFF parsing will still attempt to use the half populated fvar table and potentially access unitialized memory (https://github.com/khaledhosny/ots/blob/master/src/variations.cc#L35). I can create a fix, but was looking for thoughts on the best approach to fix this. Currently drop_variations on Font is never read by anything. I imagine we want to use that to signal that variation store instead of CFF should be dropped too.

**Comment by khaledhosny** [comment]
cc @jfkthame since most of the variation code was written by him.

**Comment by jfkthame** [comment]
I think there may be a similar bug with feature variations, too: in layout.cc's `ParseFeatureVariationsTable()`, it wants to look at the 'fvar' and doesn't check whether it was dropped (and therefore incomplete/broken).

@garretrieger if you can put together a patch to cover both these cases, that'd be awesome - thanks! I guess it'd be nicest to just discard the variation aspects and not reject the CFF or layout table entirely, if that can be done cleanly.

**Comment by garretrieger** [comment]
Looked into the CFF code some more, it looks like it currently makes no attempt to modify the CFF2 table  and only attempts to validate it by parsing the whole thing, but then serializes by writing out the input table exactly as is. Since there's no existing capability to modify the output CFF2, it's likely going to be quite a bit of work to add the capability to selectively drop variation support from the output. Unfortunately, I don't think I'd be able to undertake that.

Given that we can't safely parse and validate the CFF2 table if fvar is corrupt then I think the next safest option is to fail validation. If that sounds good, then I'll start working on making that change.
