### ISSUE TITLE
STAT table false warn again? "nameID out of range"

### ISSUE THREAD

**Issue by justvanrossum** [khaledhosny/ots#210]
This seems similar to #180, but is about an AxisNameID, which in my font refers to nameID 2. I don't see how that's illegal.

**Comment by justvanrossum** [comment]
The test for `axis.axisNameID` passes `false` for `allowPredefined`:
https://github.com/khaledhosny/ots/blob/516e40a7a37a77e082549578529c1e0cb4658184/src/stat.cc#L87-L89

**Comment by justvanrossum** [comment]
(This is btw. a side effect of fonttools more aggressively reusing name IDs.)

**Comment by khaledhosny** [comment]
This is intentional, from the [spec](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-records):
> The axisNameID field provides a name ID that can be used to obtain strings from the 'name' table that can be used to refer to the axis in application user interfaces. The name ID must be greater than 255 and less than 32768.

We probably can relax the check if there is a strong case for it, but I feel a bit uneasy about allowing spec violation in a new table with not many existing implementations as who knows what crazy stuff implementations might assume based on what the spec is saying.

**Comment by justvanrossum** [comment]
Ok, but then we have a serious problem in fonttools with name ID reusing. I'll open an issue there.

**Comment by justvanrossum** [comment]
(Thanks for your quick answer, btw.!)

**Comment by behdad** [comment]
> We probably can relax the check if there is a strong case for it, but I feel a bit uneasy about allowing spec violation in a new table with not many existing implementations as who knows what crazy stuff implementations might assume based on what the spec is saying.

Unfortunately the spec continues to encode unnecessary and bogus restrictions.  That is because of how changes to the spec are made and reflect personal opinion of the editor, not something a lot of stakeholders agree with.
