### ISSUE TITLE
Error when sanitizing an empty CFF2 CharString

### ISSUE THREAD

**Issue by aminanan** [khaledhosny/ots#217]
Unlike CFF1 a CFF2 CharString can be empty since the **endchar** operator is removed (section 4.2 of [The CFF2 CharString Format](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2charstr#4-charstring-operators)). However for an empty CFF2 CharString the sanitizer returns "Undefined operator: 0"

**Comment by khaledhosny** [comment]
I’ll need a test font.

**Comment by aminanan** [comment]
I am trying to generate and validate an OpenType font which use a CFF2 table. Once completed, I will provide it for testing. To make the font pass CharString validation, I added this test in `ExecuteCharString` function after the call to `ReadNextNumberFromCharString`:
``` 
if(length == 1 && operator_or_operand == 0){
   continue;
}
```

**Comment by aminanan** [comment]
Since the lack of support of CFF2 (Windows 10 considers the font non-valid and cannot install it), I have generated a [CFF 1 font](https://digitalkhatt.org/about#opentype) . In order to reproduce the bug, I converted the font to CFF2 using the following [afdko](https://github.com/adobe-type-tools/afdko) commands:
```
tx -cff2 +S  digitalkhatt.otf > mytable.cff2
cp digitalkhatt.otf digitalkhattcff2.otf
sfntedit -d CFF digitalkhattcff2.otf
sfntedit -a CFF2=mytable.cff2 digitalkhattcff2.otf
```
The CFF2 font generated is validated by the sanitizer without any errors. The reason is that the glyphs without outline are generated as CharStrings with length 0 (i.e., the next offset equals the glyph offset) instead of charStrings with empty byte. It seems that it is more a bug in the font than in the sanitizer even if a charString with zero byte remains valid.

**Comment by skef** [comment]
I think this may have been fixed by bd80b805 . Anyway, I believe this archive should have a valid test font. This is just a CFF2 hinted version of Source Serif Variable that has been subsetted to unicode 0x00 through 0xFF with `hb-subset` using the `--retain-gids` option. 

[ss4vrs.zip](https://github.com/khaledhosny/ots/files/10934815/ss4vrs.zip)

**Comment by skef** [comment]
Alternatively, the original font prompting this issue might have been poorly formed. It doesn't seem like a single "0" byte should be a valid CharString. Seems like something that would be generated by something that doesn't understand CFF2 CharStrings don't start with a width.

Either way, this can probably be closed.

**Comment by aminanan** [comment]
Please find a [test file](https://digitalkhatt.org/assets/fonts/ots-sanitizer-error.otf) to reproduce the error. I get the error `ERROR: CFF2: Failed validating CharStrings INDEX`. When I run TTX twice to generate the XML then the otf,
This error no longer occurs (However, there is another error in GSUB which I believe is unrelated to this one)

**Comment by skef** [comment]
@aminanan Is this message to me?

**Comment by aminanan** [comment]
@skef I saw there was status `needs test file` to fix the problem. So I uploaded one. The comment is primarily addressed to the maintainer of the package.

**Comment by skef** [comment]
Ah, OK. You're message is confusing because the first sentence isn't in a quote box, so it sounds like you're making a request.

**Comment by aminanan** [comment]
The error generated while sanitizing the test file above is caused by a `return` operator that was removed in CFF2. The originally reported error no longer occurs. Probably a previously malformed font file. I will therefore close the issue. If the problem arises again, I will file a new issue.
