### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by bobh0303** [khaledhosny/ots#218]
There have been 9 PRs merged, since 8.0 in August of 2019. What would it take to move toward a new release?

**Comment by khaledhosny** [comment]
> What would it take to move toward a new release?

Writing release notes :)

**Comment by bobh0303** [comment]
OK, here are some things gleaned from PRs:

- Update third_party/lz4
- Remove spurious component_count check
- Sanitize PS names more strictly than the spec requires
- Fixup bad entry_selector in the table directory
- Allow for new flags in Graphite Feat table
- Bugfix for google/oss-fuzz#4089
- If variation tables are dropped don't parse any other variation tables
- Remove dropped variation tables from m_table
- Remove variation tables that don't parse

Gleaning from the commit list is harder.

**Comment by khaledhosny** [comment]
Done.

**Comment by anthrotype** [comment]
Khaled, I see you have pushed a git tag for v8.1.0, but have not also made a Github Release like you have done for the past releases. E.g.
https://github.com/khaledhosny/ots/releases/tag/v8.0.0

In [ots-python] bindings, we are relying on the "ots-{version}.tar.xz" source tarball be available at the releases url: 

https://github.com/googlefonts/ots-python/blob/fec97aabc9b3f04c72f1af088da17074e46ef8f8/setup.py#L42-L45

Could you please publish a Github Release with attached tarball? Thanks

**Comment by khaledhosny** [comment]
The release was still a draft somehow, published it now. However, CI upload of built artifacts stopped working, I tried to debug it but went nowhere (Travis looks like it is working, but nothing is uploaded, AppVeyor gives and error but I could get what is causing it).

**Comment by khaledhosny** [comment]
For the source tarball, I think the GitHub generated one should be good enough.

**Comment by anthrotype** [comment]
> For the source tarball, I think the GitHub generated one should be good enough.

right. I just need to figure out the new url pattern

**Comment by anthrotype** [comment]
hm.. no, if I use the github-generated tarball, it does not contain the submodules (e.g. brotli) and building fails with:

```
src/c/ots/meson.build:48:0: ERROR: Include dir third_party/brotli/c/include does not exist.
```

**Comment by khaledhosny** [comment]
Bummer, I don’t know what to do then, may be shallow clone the repository and build from this (makes git a build dependencies so I’m not sure if its a viable option).

**Comment by anthrotype** [comment]
> shallow clone the repository

I would prefer not to rely on git clone for building from source.

maybe this error message "build/meson-dist/ots-8.1.0.tar.xz does not exist." could be a hint?
https://travis-ci.com/github/khaledhosny/ots/jobs/397715755#L1099

**Comment by anthrotype** [comment]
AH! I see what's going on:

https://travis-ci.com/github/khaledhosny/ots/jobs/397715755#L1096

you need `skip_cleanup: true` to deploy stage to avoid travis attempting to do a `git stash --all`

**Comment by khaledhosny** [comment]
Isn’t this the same as `cleanup: false`?

**Comment by anthrotype** [comment]
i have no idea, honestly

**Comment by anthrotype** [comment]
it's called `skip_cleanup` apparently, not `cleanup`: https://docs.travis-ci.com/user/deployment#uploading-files-and-skip_cleanup

**Comment by anthrotype** [comment]
the appveyor failure is unrelated, something with the auth_token.

**Comment by khaledhosny** [comment]
> it's called `skip_cleanup` apparently, not `cleanup`: https://docs.travis-ci.com/user/deployment#uploading-files-and-skip_cleanup

No idea where I got it from then (commit 6956edf554d497be9e27806f3eb2cbe2f8e28b5d).

**Comment by khaledhosny** [comment]
Travis upload is working again. Leaving the AppVeyor upload until someone complains.

**Comment by khaledhosny** [comment]
All artifacts are uploaded again now, hopefully it won’t break by the time of next release.

**Comment by anthrotype** [comment]
Thanks a lot!
