### ISSUE TITLE
What is the rationale for limiting WOFF/WOFF2 uncompressed table length to 30MB?

### ISSUE THREAD

**Issue by josh-hadley** [khaledhosny/ots#219]
Per
https://github.com/khaledhosny/ots/blob/1fe1227f2c251c2656106a004bbed83b41936b63/src/ots.cc#L633-L635

uncompressed (WOFF, WOFF2) tables are limited to 30MB. Table length limit otherwise is 1GB. What is the rationale for the 30MB limit for compressed -> uncompressed?

**Comment by khaledhosny** [comment]
I have no idea. The WOFF check is from the first implementation in a6a1b6de which predates my fork. The WOFF2 check is even worse as the whole font is checked against the 30 MB limit, from the first implementation in 96d74fe3 which also predates my fork.

You would need someone from Chrome to track down that decision.

**Comment by anthrotype** [comment]
Hm, the arbitrary limit looks strange indeed. I was told there are some large CJK fonts among macOS system fonts (e.g. `HanziPenTC-W3`) which fail OTS when compressed as WOFF or WOFF2. But they _pass_ if sanitized as uncompressed TTCs.

**Comment by josh-hadley** [comment]
@anthrotype that's exactly the situation I'm facing (large CJK fonts). No issues with the raw/uncompressed font, but the WOFF & WOFF2 files fail because of these limits.

**Comment by behdad** [comment]
The limits were put in place supposedly to protect against gzip bombs in WOFF as well as classic myopic "who needs webfonts with tables > 30MB anyway"...

**Comment by drott** [comment]
The review of a6a1b6debe569cd69a02fc5089ac8e69f4d9ba5f was here: https://codereview.appspot.com/946044 - upgrading this limit during the review from 16MB to 30MB. - In the review, Yusuke Sato compared the initial limit of 16MB to a set of Windows fonts:

> ```
> Some of unmalicious fonts seem to exceed this limitation. How about using 30MB
> or something?
> 
> fonts$ find . -size +16M -name '*tf' -ls
> -rwxr-xr-x   1 yusukes        27382464 Aug 25  2009 ./windows/mingliu0.ttf
> -rwxr-xr-x   1 yusukes        27382472 Aug 25  2009 ./windows/mingliu1.ttf
> -rwxr-xr-x   1 yusukes        27396928 Aug 25  2009 ./windows/mingliu2.ttf
> -rwxr-xr-x   1 yusukes        23278008 Jul  1  2009 ./mac/Arial\ Unicode.ttf
> ```

So I assume 30MB was set to include those.

No objections to raising it if that's needed. Which change or size limit change did you have in mind, @josh-hadley?

**Comment by josh-hadley** [comment]
Thanks @drott -- I'd like to increase both the table and overall font size limits enough to avoid having to revisit this in the next couple of years 😄  . But I do want to respect the protections against gzip bombs as @behdad pointed out (as well as any other external limits that might be in play at the OS or browser level).

I think bumping the table limit by 5X the current limit (to 150MB) and the overall font size by 10X (to 300MB) is reasonable, but may still be a bit short-sighted. I have seen non-system fonts that are already nearing a file size of 40MB and I'm sure there are larger ones around. Some of the [Source Han Super OTC files](https://github.com/adobe-fonts/source-han-super-otc/releases/tag/20190603) that Ken Lunde made a while back are nearing 400MB total file size (doubtful those would be in play as webfonts anytime soon but who knows?).

**Comment by jfkthame** [comment]
Agreed - keeping some kind of limit (before hitting "run out of address space") is probably good, but these suggested increases seem OK to me for now.

**Comment by jackyjjc-canva** [comment]
@josh-hadley, I ran into this issue today. While this change does remove the limit from the OTS side, it still fails [when it calls `woff2::ConvertWOFF2ToTTF`](https://github.com/khaledhosny/ots/blob/27d63ae4d8988619e0a661bf40551c47da47f3fa/src/ots.cc#L547).

The issue is that the constructor of `WOFF2StringOut` [sets the maxSize](https://github.com/google/woff2/blob/0f4d304faa1c62994536dc73510305c7357da8d4/src/woff2_out.cc#L14) of the buffer to `kDefaultMaxSize`, which is also set to [30MB](https://github.com/google/woff2/blob/0f4d304faa1c62994536dc73510305c7357da8d4/include/woff2/output.h#L20)

To properly fix this, we will need to ensure the maxSize of the output buffer is set correctly, something like this:
```
diff --git a/src/ots.cc b/src/ots.cc
index ed22b8c..8424e02 100644
--- a/src/ots.cc
+++ b/src/ots.cc
@@ -544,6 +544,7 @@ bool ProcessWOFF2(ots::FontFile *header,

   std::string buf(decompressed_size, 0);
   woff2::WOFF2StringOut out(&buf);
+  out.SetMaxSize(decompressed_size);
   if (!woff2::ConvertWOFF2ToTTF(data, length, &out)) {
     return OTS_FAILURE_MSG_HDR("Failed to convert WOFF 2.0 font to SFNT");
   } 
```

Am I understanding this correctly or am I missing some important context?

**Comment by josh-hadley** [comment]
@jackyjjc-canva yeah I think that was overlooked when this issue last came up 4 years ago because the limit was still far beyond anything likely to be seen in a web font at that time. I suggest working up a patch that increases the uncompressed limit and see what the project maintainers think.
