### ISSUE TITLE
Need help with font rendering error - Non zero cmap subtable segment padding (50111)

### ISSUE THREAD

**Issue by d-amruta** [khaledhosny/ots#241]
Hello,

We are seeing font rendering issues with sample PDF file in our web application. The web application is deployed in Tomcat on Linux system (CentOS Linux 7) and we use pdf.js library for PDF display. We noticed that text in the PDF is rendered as white boxes or unusual symbols and noticed some errors in Firefox and chrome console. The issue is observed when PDF file contains Embedded Subset fonts. We also noticed that we get different results with different host environments. When we have our application deployed using Docker container, the PDF seems to render better. Here are details environment where issue is observed - 

Web browsers: Chrome Version - 98.0.4758.102, Firefox - 97.0.1 (64-bit)
Operating system: CentOS Linux 7 (Core) Kernel: Linux 3.10.0-1160.15.2.el7.x86_64
Tomcat (Version: 9.0.45)
PDF.js version: 2.2.228 

We would like to understand what is causing the embedded fonts in PDF file getting rejected by OTS in one environment and not other. Also if you could share some info about what is causing the error -` downloadable font: cmap: Non zero cmap subtable segment padding (5011)`, then it would be really helpful.

Please find the attached screenshots for Chrome and Firefox console errors - 

![font_error_chrome](https://user-images.githubusercontent.com/99489253/155519040-701fdea9-c72e-457d-8882-c51087cb44ba.PNG)
![font_errors_firefox](https://user-images.githubusercontent.com/99489253/155519059-3990c428-357f-48a5-b5e0-afa2d46e4ad3.PNG)

Here is sample PDF file  -
[Test-Font-Rendering.pdf](https://github.com/khaledhosny/ots/files/8132229/Test-Font-Rendering.pdf)

**Comment by khaledhosny** [comment]
You probably need to raise the issue with pdf.js as AFAIK, it does a quite bit of processing for the fonts since most fonts embedded in PDF files are unusable as it on the web. This particular error means that the `reservedPad` field of [Format 4 `cmap` subtable is not set to zero as it should](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values), so whatever generated the font (or the table), generated one that does not conform to the spec.

**Comment by d-amruta** [comment]
Thank you for taking a look and quick response. We have reported this issue with pdf.js ([14556](https://github.com/mozilla/pdf.js/issues/14556)). Regarding your observation for the error, we would like to understand, can host environment affect fonts parsing by OTS? Any suggestion for troubleshooting this error would be really helpful

**Comment by khaledhosny** [comment]
Host environment shouldn’t make a difference.

**Comment by d-amruta** [comment]
Ok. Thank you for sharing inputs for all previous questions. One last question - Do you think system fonts can cause this issue?
Appreciate your help!

**Comment by d-amruta** [comment]
Ok. Thank you for sharing inputs for all the queries. It truly helps.
