### ISSUE TITLE
wrong ots-idempotent return code ?

### ISSUE THREAD

**Issue by bhoehl** [khaledhosny/ots#243]
file util/ots-idempotent.cc contains a return code that is probably wrong:

  // Verify that original font can be opened by the font renderer. If this
  // fails then no point in verfying the transcoded font.
  if (!VerifyTranscodedFont(in.data(), in.size())) {
    std::fprintf(stderr, "Failed to verify the original font\n");
    return 0;
  }

it should return 1 on failure ?!

**Comment by khaledhosny** [comment]
This is checking that the system API can load the original, unmodified, font before trying to load the modified one. If loading the original font fails, then this is not our bug and we don’t want to fail here.

**Comment by bhoehl** [comment]
Sounds reasonable, if the system can´t load the modified font, that should be sufficient.
