### ISSUE TITLE
Binary release doesn’t work in M1 macs

### ISSUE THREAD

**Issue by schriftgestalt** [khaledhosny/ots#246]
I downloaded the binary mac version. It gives this error:
```
dyld[29869]: Library not loaded: '/usr/local/opt/lz4/lib/liblz4.1.dylib'
  Referenced from: '/Users/georg/Downloads/ots-8.2.1-macOS/ots-sanitize'
  Reason: tried: '/usr/local/opt/lz4/lib/liblz4.1.dylib' (no such file), '/usr/local/lib/liblz4.1.dylib' (no such file), '/usr/lib/liblz4.1.dylib' (no such file)
```
Installing lz4 with brew gave results in this error:
```
dyld[81357]: Library not loaded: '/usr/local/opt/lz4/lib/liblz4.1.dylib'
  Referenced from: '/Users/georg/Downloads/ots-8.2.1-macOS/ots-sanitize'
  Reason: tried: '/usr/local/opt/lz4/lib/liblz4.1.dylib' (no such file), '/usr/local/lib/liblz4.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/lib/liblz4.1.dylib' (no such file)
```
(brew installed the arm version of the lib and I didn’t manage to make it install the intel version)

Could that lib be statically linked that one doesn’t need to install it?

And It would be nice to have a Universal binary.

I have MacOS 12.5.1

**Comment by anthrotype** [comment]
I know it's not the same thing, but the python wrapper for ots can be run from the command line as well and comes with universal2 (arm64 + x86_64) mac wheels:

https://github.com/googlefonts/ots-python/releases/tag/v8.2.1

You run as `python -m ots` (instead of `ots-sanitize`) and works the same way.

**Comment by schriftgestalt** [comment]
And running setup from within the ots-python folder doesn't work either
```
downloading https://github.com/khaledhosny/ots/releases/download/v8.2.1/ots-8.2.1.tar.xz
error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```
(I have python 3.10 from python.org)

**Comment by anthrotype** [comment]
pip install certifi then retry, looks like you're missing some SSL certificates

**Comment by anthrotype** [comment]
(when installing Pythons for macOS downloaded from python.org, you need to run the "Install Certificates.command" file installed into the /Applications/Python 3.x" folder, which basically installs the `certifi` package with pip)

**Comment by khaledhosny** [comment]
Hmm, we should be statically linking, but apparently we are not.

**Comment by khaledhosny** [comment]
Can you try https://github.com/khaledhosny/ots/releases/tag/v8.2.2

**Comment by khaledhosny** [comment]
8.2.2 binaries work for me.

**Comment by schriftgestalt** [comment]
Works. Thanks.
