### ISSUE TITLE
New release with COLR/CPAL support?

### ISSUE THREAD

**Issue by jfkthame** [khaledhosny/ots#248]
I know 8.2.2 just came out last week, but the addition of COLR/CPAL support seems significant enough to justify doing another release soon, if possible.

(I'm hoping to merge this in Firefox in the v.107 dev cycle, which starts in a couple days, and it's tidier if we can just take a specific tagged release rather than pulling arbitrary commits from main. Thanks!)

**Comment by khaledhosny** [comment]
https://github.com/khaledhosny/ots/releases/tag/v9.0.0

**Comment by jfkthame** [comment]
Thanks, that was quick! 👍

**Comment by khaledhosny** [comment]
We don’t have much of release cadence here, releases are cut at whim 😄
