### ISSUE TITLE
Required tables?

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#26]
In Firefox I see OTS erring that my font doesn't have OS/2 table.  My local build doesn't complain about that.  Couldn't find the change that caused that in a quick look.  At any rate, just opening this ticket so we can discuss the required tables that OTS is a**l about and what they should be.

**Comment by HinTak** [comment]
"require what's actually required by platforms we care about" is a rather dangerous thought - quite a few past design decisions in MS FontVal I do not wish to engage and argue with anybody about, comes from that school of thought - "if we make this (our preference) a requirement, it makes our life (in Microsoft) easier".

**Comment by khaledhosny** [comment]
So there are required table and there are “required” tables; there are the tables that OTS thinks are required and there are the tables that it needs to check other tables (for example `maxp` is needed for parsing many tables as the number of glyphs is taken from it).

There is not much we can do about the later. For the former I think we can either keep things the way there are now as long as it is not getting on the way, or start testing what the minimal set of tables needed by Firefox and Chrome to be able to show webfonts on the platforms they support. I’m inclined to just do nothing unless it is really getting in the way of things people want to do.
