### ISSUE TITLE
Fixup passthru vs required-table interaction

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#27]
Following up from latest comments on:

  https://bugzilla.mozilla.org/show_bug.cgi?id=833283

Lets fix the issue with passthru tables not correctly being recognized as being present.

**Comment by khaledhosny** [comment]
This should be fixed now, mostly. Still if we need some field from a table to parse another and that said table have been passthru, we will fail. I don’t think there is much to do about that case, though.
