### ISSUE TITLE
feat: release binaries for linux-arm64

### ISSUE THREAD

**Issue by jlarmstrongiv** [khaledhosny/ots#274]
MacOS has binaries that work for both `amd64` and `arm64`.  It would be great to support `arm64` for linux too.

I have confirmed that the project builds and runs successfully in `arm64`:

```shell
# docker
# docker run -it --entrypoint /bin/bash --rm public.ecr.aws/lts/ubuntu:jammy
# ubuntu
apt-get update
# meson dependencies https://mesonbuild.com/SimpleStart.html
apt install build-essential -y
apt install meson ninja-build -y
apt install wget -y 
# wget 
wget https://github.com/khaledhosny/ots/releases/download/v9.1.0/ots-9.1.0.tar.xz && tar xf ots-9.1.0.tar.xz && cd ots-9.1.0 && meson --wrap-mode=forcefallback --buildtype=release --strip -Ddebug=true --prefix="$(pwd)/dist" build
ninja -C build
```

GitHub actions supports cross-architecture builds with `docker/setup-qemu-action`.

Or, third-party build runners are available for linux arm64:
- https://www.ubicloud.com/blog/ubicloud-hosted-arm-runners-100x-better-price-performance
- https://buildjet.com/for-github-actions/docs/guides/migrating-to-arm

**Comment by khaledhosny** [comment]
The binaries are provided for the platforms we build on CI, and I’m not doing anything special to make macOS binaries work for ARM, they probably work through OS built-in emulation.

**Comment by jlarmstrongiv** [comment]
While MacOS binaries can be run with emulation for arm64, unfortunately linux x86_64 binaries cannot be run on linux arm64.  But, it should be possible to cross compile the linux binaries for arm64 in the CI.  I’d be glad to test cross-compiled binaries if you re-open this issue!

**Comment by khaledhosny** [comment]
I wouldn't know how to do it, but if someone can send a PR, I’ll review and merge.
