### ISSUE TITLE
Font with dummy, but correct STAT table gets rejected

### ISSUE THREAD

**Issue by drott** [khaledhosny/ots#276]
Compare review of https://chromium-review.googlesource.com/c/chromium/src/+/5361874

From W3C WPT Canvas tests: 
```
$ ttx -tSTAT -o- wpt/fonts/CanvasTest-ascent256.ttf
Dumping "third_party/blink/web_tests/external/wpt/fonts/CanvasTest-ascent256.ttf" to "<stdout>"...
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.46">

Dumping 'STAT' table...
  <STAT>
    <Version value="0x00010000"/>
    <DesignAxisRecordSize value="0"/>
    <!-- DesignAxisCount=0 -->
    <!-- AxisValueCount=0 -->
  </STAT>
```

OTS rejects this STAT table, which in my opinion, is an incorrect rejection. The STAT table may not be particularly meaningful but the presence of a STAT table might be needed for some layout engines to recognize the font as variable.

**Comment by drott** [comment]
CC @jfkthame

**Comment by jfkthame** [comment]
The rejection is because of `<DesignAxisRecordSize value="0"/>`, right? If the axis count is zero, we don't really need to check the axis record size, I guess.

> The STAT table may not be particularly meaningful but the presence of a STAT table might be needed for some layout engines to recognize the font as variable.

...but this font //isn't// variable, is it? And if it had an `fvar` table defining any axes, then the `STAT` table would also have to be non-empty.

Still, for a non-variable font that doesn't want to provide any style attributes, I suppose the dummy table ought to be valid (though pointless).

**Comment by drott** [comment]
> ...but this font //isn't// variable, is it?
True, `$ ttx -l ./external/wpt/fonts/CanvasTest-ascent256.ttf |  grep fvar` comes back empty, no `fvar` table. Sorry for the confusion - in any case what I meant to say: No need to be overly strict here and reject a font with a pointless `STAT`  table. From what you're writing it seems we agree on that. 

> And if it had an fvar table defining any axes, then the STAT table would also have to be non-empty.

Perhaps so according to the letter of the OpenType spec. But in Chromium, we would not reject a variable font even without a STAT table when loaded as a web font. (For size reduction reasons, ) There's no strict technical need to have one for the use in a a src descriptor of a @font-face declaration.

**Comment by jfkthame** [comment]
> But in Chromium, we would not reject a variable font even without a STAT table when loaded as a web font.

That's reasonable, I think -- yes, it's not technically needed. But if there _is_ a `STAT` table then it should be sufficiently complete to cover the axes present in the `fvar` (although the code doesn't currently check this; see TODO comment later in the source).
