### ISSUE TITLE
FF warning "bad weight: 1"

### ISSUE THREAD

**Issue by Pomax** [khaledhosny/ots#49]
full error, including full font base64 encoded:

```
downloadable font: OS/2: bad weight: 1 (font-family: "PjsEmptyFont" style:normal weight:normal stretch:normal src index:0) source: data:application/x-font-ttf;base64,AAEAAAAKAIAAAwAgT1MvMgAAAAAAAAEoAAAAVmNtYXAAAAAAAAABiAAAACxnbHlmAAAAAAAAAbwAAAAkaGVhZAAAAAAAAACsAAAAOGhoZWEAAAAAAAAA5AAAACRobXR4AAAAAAAAAYAAAAAGbG9jYQAAAAAAAAG0AAAABm1heHAAAAAAAAABCAAAACBuYW1lAAAAAAAAAeAAAAAgcG9zdAAAAAAAAAIAAAAAEAABAAAAAQAAAkgTY18PPPUACwAgAAAAALSRooAAAAAAyld0xgAAAAAAAQABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAACAAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMAIwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAMAAQAAAAwABAAgAAAABAAEAAEAAABB//8AAABB////wAABAAAAAAAAAAgAEgAAAAEAAAAAAAAAAAAAAAAxAAABAAAAAAABAAEAAQAAMTcBAQAAAAAAAgAeAAMAAQQJAAEAAAAAAAMAAQQJAAIAAgAAAAAAAQAAAAAAAAAAAAAAAAAA
```

This seems wrong - weights can range the full gamut of the USHORT type reserved for the OS/2 weightClass. By convention, most fonts use the "steps of 100" system (and even then only using the values 100 through 900), but this isn't a formal requirement in the OpenType spec at all, so should not be considered erroneous. Any value  of 1 or higher is a fully legal font weight.

**Comment by khaledhosny** [comment]
Though I think you are right, in the defense of whoever wrote this code, [http://www.microsoft.com/typography/otspec/os2.htm#wtc](the spec) is rather vague here; it lists the values from 100 to 900 in steps of 100, but it does not explicitly state that those are the (or are not) the only allowed values. Anyway the warning is useless (and the code changing the weight class of the affected fonts is even so) as I don’t see what harm this can make.

**Comment by behdad** [comment]
Actually common wisdom is to multiply it by 100 if it's a single-digit number as it's probably set by mistake.

That's what Microsoft recommends, and fontconfig does as well.  See:
https://bugs.freedesktop.org/show_bug.cgi?id=82228

https://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-components-postattachments/00-02-24-90-36/WPF-Font-Selection-Model.pdf (page 4, bottom)

**Comment by khaledhosny** [comment]
Hmm, should we set `usWeightClass >= 1000` to `999` as well, then?

**Comment by Pomax** [comment]
I'm not sure it makes sense to even bother with that check at all. There are fonts out there that don't use the 100-900 convention, warning that they have bad weights, when the spec says nothing about that, seems like pretending to know more than is actually true

**Comment by behdad** [comment]
> Hmm, should we set usWeightClass >= 1000 to 999 as well, then?

I don't know.

**Comment by khaledhosny** [comment]
OK, I pushed a change anyway to remain closer to the previous behaviour, least Windows API’s start rejecting fonts they were accepting before.
