### ISSUE TITLE
tag versions of ots shipped by various firefox and chrome versions

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#54]
Old versions of Chrome don't log ots failures.  So when fonts fail, the only way to know which of the old issues are causing it, one has to build old versions of ots and try...  Would be nice to tag good commits to try with tags like chrom38, firefox34, etc.

In the case I was debugging this was already fixed in https://github.com/khaledhosny/ots/issues/1

**Comment by khaledhosny** [comment]
I tagged revisions used in Chrome up to v19. Mozilla’s git mirror does not seem to tag releases, so I couldn’t map OTS revisions to Firefox releases, will give the mercurial repository a look.

**Comment by behdad** [comment]
Thanks Khaled.

**Comment by khaledhosny** [comment]
Revisions used up to Firefox 17 are tagged now as well.
