### ISSUE TITLE
Support OpenType 1.7

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/ots#55]
Check if there are any changes needed in OTS.

**Comment by behdad** [comment]
Do we support the version 5 OS/2 table?  That's the only thing that comes to my mind.

**Comment by khaledhosny** [comment]
Not yet (that is the one I had in mind to, but it does not harm to check the rest of the changes).

**Comment by khaledhosny** [comment]
It seems that no more changes is needed indeed.
