### ISSUE TITLE
Generate glyph names for TrueType fonts with post version 3 tables?

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/ots#56]
That would be stretching the role of OTS a bit, but some webfonts use `post` version 3 table to save space, however it seems that [some environments](http://typedrawers.com/discussion/comment/11714/#Comment_11714) behave different when glyph names are missing.

**Comment by behdad** [comment]
Interesting...

**Comment by twardoch** [comment]
I have something in the works, using fontTools.

**Comment by khaledhosny** [comment]
Too much of a change in font behavior, if font developers cares about this they should be adding the glyph names themselves.
