### ISSUE TITLE
autotools

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#57]
I see you have a autotools branch.  Any plans to replace the build system with that one?

**Comment by khaledhosny** [comment]
This was partly motivated by the need to use gtest properly (see #46) as gyp seems to be very poorly documented, so I was naturally waiting until this is actually done before merging the branch. I’m also a bit reluctant as some people seem to be building OTS on Windows, and I’m not sure how hard is it to build using autotools there.

**Comment by behdad** [comment]
Given that this tool is not for end users, I'm not sure if I mind much about the Windows issue...

We can set up one of the continuous CI systems to build Windows binaries for every tag...  Anyway, your call.  The current build system is a-ok for the project as is.

**Comment by khaledhosny** [comment]
I merged the autotools branch. Lets figure the CI stuff when there is a real demand.
