### ISSUE TITLE
WOFF2 decoder fails to reconstruct unpadded glyf table

### ISSUE THREAD

**Issue by anthrotype** [khaledhosny/ots#60]
same as https://github.com/google/woff2/issues/15

**Comment by anthrotype** [comment]
actually, the issue here seems slightly different from the one in the reference [woff2](google/woff2#15) decoder.
Since commit https://github.com/khaledhosny/ots/commit/27a1ef3ba029cd45c63d9d54ec832feef0102ad7, OTS always generates 2-byte aligned glyf table instead of the former 4-byte aligned -- which is still the case in the current reference decoder.

This means that:

- if the original sfnt glyf table of a WOFF2 font is padded to multiples of 2 bytes (which is required for "short" loca version with indexFormat 0), OTS will **not** fail to decode the font -- while reference woff2 decoder will still fail, since it always expects a 4 byte aligned glyf table  (ping @rsheeter).

- if the original sfnt font of a WOFF2 font uses the "long" loca format (indexFormat 1) and has no padding between glyphs entries (neither 4 nor 2 byte padding), then both OTS and ref decoder fail to decode the WOFF2 font.

I hope this helps to clear the issue a little bit.
Thank you,

Cosimo

**Comment by khaledhosny** [comment]
Closing this, as it is tracked now in google/woff2#15 (and we will soon switch to that code).
