### ISSUE TITLE
gyp?

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#69]
code.google.com is going down, and currently the build requires checking out gyp from code.google.com svn.

**Comment by davelab6** [comment]
https://groups.google.com/forum/#!searchin/gyp-developer/code.google.com/gyp-developer/KS2xk4MGpyw/OLfVLRI-SWkJ looks like https://chromium.googlesource.com/external/gyp/ is the new upstream git repo

**Comment by khaledhosny** [comment]
Gyp? We got rid of this like the last decade :)

**Comment by davelab6** [comment]
It seems still needed for https://github.com/khaledhosny/ots/archive/chrome-42.zip

**Comment by khaledhosny** [comment]
How I’m supposed to fix the link for past history?

**Comment by davelab6** [comment]
Cut a new release :)

**Comment by khaledhosny** [comment]
These are not releases but tags of the revisions used by those specific versions of Firefox or Chrome, so they are frozen in time.

**Comment by davelab6** [comment]
Right but to package the program I need you to make a release so there is a
src tarball to checksum :)

**Comment by khaledhosny** [comment]
That is a totally different issue, those tags are not releases.

**Comment by davelab6** [comment]
hmm.

<img width="730" alt="screen shot 2015-07-10 at 12 26 52" src="https://cloud.githubusercontent.com/assets/261579/8623347/f7a1a4c4-26fe-11e5-83c4-bff2eb216be7.png">

**Comment by khaledhosny** [comment]
I think it is just GitHub assuming any tag is a release, which is makes no sense.
