### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#70]
While github presents tags as releases (which makes no sense) some packaging systems requite in addition to the 'head' git repo URL a 'static' release tarball URL. 

Therefore to package ots, I'd like to request making a tag with a semver.org style version in order to present that as the most recent release.

**Comment by davelab6** [comment]
Thanks boss

**Comment by davelab6** [comment]
However, I now realised that https://github.com/khaledhosny/ots/blob/master/autogen.sh#L3-L13 is not meaningful when downloading https://github.com/khaledhosny/ots/archive/v4.0.0.tar.gz and trying to build that. Hmm.

**Comment by khaledhosny** [comment]
You shouldn’t need to run `autogen.sh` on release tarball, which I didn’t actually upload as there was several issues with `make dist` and I got distracted. I made a new release, you should use the `ots-4.0.1.tar.gz` tarball not the one GitHub makes from the tag.
