### ISSUE TITLE
parse error : CFF table in NotoSansCJK / SourceHanSans (full 64k version) 

### ISSUE THREAD

**Issue by jungshik** [khaledhosny/ots#75]
I haven't tested this with a standalone OTS. This is based on what Blink does. 
This comes from googlei18n/noto-cjk#28

* Grab NotoSansCJKjp-Regular.otf (from googlei18n/noto-cjk )  or the corresponding SourceHanSans-Regular.otf (this is the full 64k glyph version with JP default glyphs [1])

* Make an html page with the following contents with the font in the same directory:

```
<html>
  <head>
    <meta charset="utf-8">
    <style>
      @font-face {
        font-family: notocjkjp; 
        src: url(NotoSansCJKjp-Regular.otf) format("opentype");
        font-weight: 400;
      }
    </style>
  </head>
  <body>
  <div style="font-family: notocjkjp;">
    今週は皆様にお知らせがあります。ウィキぺディアの援助をお願
  </div>
  </body>
</html>
```
* Load the above page in Chrome and Firefox. 

* Right-click 'Inspect Element' and go to 'Console'

* Console (firefox) has the following:

```
downloadable font: CFF: Failed validating charstring set 0 (font-family: "notocjkjp" style:normal weight:normal stretch:normal src index:0) source: http://localhost:8080/fonts/NotoSansCJKjp-Regular.otf notocjk_full.html:5:18
downloadable font: CFF : failed to parse table (font-family: "notocjkjp" style:normal weight:normal stretch:normal src index:0) source: http://localhost:8080/fonts/NotoSansCJKjp-Regular.otf notocjk_full.html:5:18
downloadable font: rejected by sanitizer (font-family: "notocjkjp" style:normal weight:normal stretch:normal src index:0) source: http://localhost:8080/fonts/NotoSansCJKjp-Regular.otf notocjk_full.html:5:18
```
* Console (Chrome) has the following:

```
Failed to decode downloaded font: http://localhost:8080/fonts/NotoSansCJKjp-Regular.otf
notocjk_full.html:1 OTS parsing error: CFF : failed to parse table
```

[1] See file:///usr/local/google/home/jungshik/Downloads/SourceHanSansReadMe.pdf

**Comment by khaledhosny** [comment]
CFF is a big cryptic to me, but it seems that OTS does not like the fact that the top DICT has zero number of CharStrings offsets. It specifically fails on this line https://github.com/khaledhosny/ots/blob/master/src/cff_type2_charstring.cc#L858 (funnily, if I remove this check, we don’t seem to try validating any other charstrings in that font).

Now, someone who really understands CFF needs to asses this and decide what should be done here.

**Comment by behdad** [comment]
I'm guessing that the cast to 16bit is failing maybe?

**Comment by behdad** [comment]
Yep, if I add a print:

```
  const uint16_t num_offsets = 
      static_cast<uint16_t>(char_strings_index.offsets.size()); 
  printf ("%d %d\n",num_offsets, char_strings_index.offsets.size()); 
  if (num_offsets != char_strings_index.offsets.size() || num_offsets == 0) { 
    return OTS_FAILURE();  // no charstring. 
  } 
```

I get:

0 65536

If I remove the cast and check, it still fails.  I'll spend another ten minutes on it.

**Comment by behdad** [comment]
Yep, this does it:

```diff
diff --git a/src/cff_type2_charstring.cc b/src/cff_type2_charstring.cc
index a164ec1..399452e 100644
--- a/src/cff_type2_charstring.cc
+++ b/src/cff_type2_charstring.cc
@@ -852,14 +852,13 @@ bool ValidateType2CharStringIndex(
     const std::vector<CFFIndex *> &local_subrs_per_font,
     const CFFIndex *local_subrs,
     Buffer* cff_table) {
-  const uint16_t num_offsets =
-      static_cast<uint16_t>(char_strings_index.offsets.size());
-  if (num_offsets != char_strings_index.offsets.size() || num_offsets == 0) {
+  const unsigned int num_offsets = char_strings_index.offsets.size();
+  if (num_offsets == 0) {
     return OTS_FAILURE();  // no charstring.
   }
 
   // For each glyph, validate the corresponding charstring.
-  for (uint16_t i = 1; i < num_offsets; ++i) {
+  for (unsigned int i = 1; i < num_offsets; ++i) {
     // Prepare a Buffer object, |char_string|, which contains the charstring
     // for the |i|-th glyph.
     const size_t length =
```

Who knows what the person writing this code was thinking...

**Comment by kenlunde** [comment]
Check the size of the 'CFF ' table. Some font consumers have a 16MB threshold when dealing with this table. When subroutinized (via the AFDKO `makeotf` tool), all of the 65,535-glyph CFFs in Noto Sans CJK (and thus Source Han Sans) are under 16MB, with the Black/Heavy weight butting right up against it. If the subroutines are flattened, and if memory serves, all seven 65,535-glyph CFFs exceed 16MB in size. Anyway, this may serve as a clue.

**Comment by kenlunde** [comment]
@behdad: The "0 65536" in your post right above also provides a clue, because 65536 is not a valid GID (or CID). This largest GID in a CID-keyed CFF is 65534. I cannot speak to the `glyf` table, but I am sure that GID+65536 is not valid, though GID+65535 might be.

**Comment by behdad** [comment]
The 65536 is not a gid, it's the number of entries in the charstring offsets array.  My intuition says it's correct.  It's one more than the number of glyphs.  The same way that the 'loca' table in a TrueType table has 1+numGlyphs entries.

**Comment by kenlunde** [comment]
@behdad: Understood, but my guess is that it is one more than the highest GID (meaning 65535), not one more than the number of glyphs. The initial zero suggests this. I suggest that you decrement that value by one to see whether the problem goes away.

**Comment by behdad** [comment]
As far as I understand the problem already goes away if I remove the cast.

**Comment by khaledhosny** [comment]
> I get:
> 
> 0 65536
> 
> If I remove the cast and check, it still fails.  I'll spend another ten minutes on it.

Yes, that cast is suspicious, but I assumed the wrapping around was intentional.

**Comment by behdad** [comment]
I can't imagine why that would be.

**Comment by kenlunde** [comment]
I am not sure whether this helps, but the last paragraph on page 367 of my latest book explains the 64K glyph limit:

Today’s font formats, such as those based on PostScript and TrueType outlines, are limited to 64K glyphs. For name-keyed PostScript fonts, the limit is 64,000 glyphs. For CID-keyed or GID-based fonts, the limit is slightly higher, a true 64K, specifically 65,535 glyphs. Given that the first CID or GID (Glyph ID, also meaning glyphs) is 0, this means that the highest possible value is at index 65534. For OpenType fonts, to include TrueType, the maximum GID is controlled by the maxp.numGlyphs value. (In other words, the numGlyphs value in the ‘maxp’ table.) 0xFFFF (65,535) is the largest possible value for this ‘maxp’ table field; because this value represents the number of glyphs, which includes GID at index 0, it means that the valid GID range is thus 0 through 65534 (65,535 GIDs).

**Comment by kenlunde** [comment]
Anyway, this really smells like an *off-by-one* error to me.

**Comment by behdad** [comment]
No.  The font has 65535 glyphs (including .notdef), and hence an INDEX structure with count items has count+1 offsets stored in it (see 5176.CFF section 5 / table 7).

```
Offset offset
[count+1] Offset array (from byte preceding
object data)
```

**Comment by khaledhosny** [comment]
OK, that is a regression introduced in 401b45694fd7f94a3343616e2bf5461b46d2f273, so it looks like a misguided fix to compiler warnings. The original code was essentially what Behdad is proposing.

**Comment by khaledhosny** [comment]
I think this can be closed now. I also don’t get any warnings on our MSVC build, but may be Chrome enables more warnings (or our build does not enable any), I appreciate any input here.

**Comment by jungshik** [comment]
Thanks. I'll update Chrome's OTS and see if there's any warning from MSVC.
