### ISSUE TITLE
Consider accepting Google-style (CBLC/CBDT) color fonts?

### ISSUE THREAD

**Issue by rsheeter** [khaledhosny/ots#79]
OTS rejects Google-style color fonts (such as Noto Color Emoji) saying "OTS parsing error: no supported glyph shapes table(s) present". 

Perhaps we should accept fonts that have CBDT/CBLC? - the font I tested with had ['head', 'hhea', 'maxp', 'OS/2', 'hmtx', 'cmap', 'name', 'post', 'CBDT', 'CBLC', 'GSUB'] and was working until I updated Chrome and evidently picked up a new OTS.

**Comment by khaledhosny** [comment]
Chrome should be telling OTS to pass thru these tables, but if this stopped working after upgrade then it might be related to 097291983d12fb662e9aed677b556fd539aff436 (but it would be very surprising if none of Chrome tests caught this during development).

**Comment by rsheeter** [comment]
Odd. I was testing with Chrome, it was working, I allowed Chrome to update
(from I'm not quite sure what to 46.0.2490.80), and it stopped working. My
font never had any of the usual tables so it seemed to be tied to the
update.

**Comment by khaledhosny** [comment]
I think Chrome just updated to a buggy revision of OTS, so they have the issue that was fixed in the above commit.

**Comment by behdad** [comment]
cc @rsheeter @drott

**Comment by irori** [comment]
Yeah, Chrome >=46 has a bad revision of OTS. :(
https://code.google.com/p/chromium/issues/detail?id=548124

**Comment by behdad** [comment]
This whole "machine-endian" vs "big-endian" is really confusing.  I'd rather we just say the tag passed to GetTableAction() is formed using OTS_TAG.

**Comment by khaledhosny** [comment]
Probably it is confusing because I’m confused and don’t know what I’m doing here :) I think we now handle tags like everyone else, not sure how to convey this without making it sound you have to use `OTS_TAG`.

**Comment by behdad** [comment]
It's ok to make it sounds as if they have to use OTS_TAG().  It's a public macro, so it's clear what the expectation is.

**Comment by rsheeter** [comment]
+1 for directly saying "use OTS_TAG". FAR simpler than having to worry about which-endian.

**Comment by khaledhosny** [comment]
OK, `OTS_TAG()` is mentioned explicitly now.
