### ISSUE TITLE
Web based service 

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#85]
@Impallari suggested setting up a web service to make submitting fonts via web form easy, to avoid autotools installation fun. 

Formally it's a separate project but I wanted to file an issue here to track the need.

**Comment by behdad** [comment]
emscripten sounds easier to set up.

**Comment by khaledhosny** [comment]
@davelab6 is there still a need for this, doesn’t fontbackery handle this in some way now?

**Comment by davelab6** [comment]
Yes, FB handles this
