### ISSUE TITLE
Setup a PPA with prebuild deb packages

### ISSUE THREAD

**Issue by felipesanches** [khaledhosny/ots#86]
In addition to the general usefulness of it, doing so will also make it easier for people to setup Travis CI jobs that use ot-sanitizer, as described here: https://github.com/googlefonts/fontbakery/issues/615

cheers!
Felipe

**Comment by khaledhosny** [comment]
Someone else will have to do it, I deactivated my launchpad account a while ago.

**Comment by davelab6** [comment]
Can you assign felipe? :)

**Comment by khaledhosny** [comment]
You can’t assign to a non-collaborator it seems.

**Comment by behdad** [comment]
How hard would it be to build ots in their travis instance?

**Comment by felipesanches** [comment]
@behdad , we already do build it from source on Travis. But having a deb package would make it more convenient.
