### ISSUE TITLE
are memory usage fields in 'post' table format 1 and 3 optional?

### ISSUE THREAD

**Issue by anthrotype** [khaledhosny/ots#93]
At least from my reading of the OpenType (and TrueType) spec, the 'post' table should always contain the last four fields about memory usage, however useless they might be.
The spec just says:

> If it is not known, set the value to zero.

This means that the minimal length of the post table should be at least 32 bytes, not 16.

OTS does raise an error if it cannot skip past the four memory fields, but only if the post version is 2. When it's 1 or 3, it returns successfully, before attempting to skip them.

https://github.com/khaledhosny/ots/blob/master/src/post.cc#L34-L47

Just sayin'.

**Comment by khaledhosny** [comment]
Yes, the code looks bogus.
