### ISSUE TITLE
[build] Autogen.sh expects git checkout and will not work with tar.gz

### ISSUE THREAD

**Issue by eosrei** [khaledhosny/ots#94]
The recommended way to build is from a git checkout according to INSTALL. There is a tar.gz source archive, so it should work.
```
user@server ~/ots-5.0.0 $ ./autogen.sh 
checking for git... *** No git found, please install it ***
```

**Comment by khaledhosny** [comment]
That is by design, you don’t need it for release tarball. It is not even included in release tarballs. It seems that I failed to upload 5.0.0 release tarball, so I guess you are building from the auto-generated one that GitHub insists to generate. My fault, I uploaded the tarball now.

**Comment by eosrei** [comment]
Ah! Yes, I tried the tarball first since that's what I'd normally use to compile something. Works now. Thanks!
