### ISSUE TITLE
What does maxp != 0 mean?

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#98]
https://github.com/khaledhosny/ots/blob/master/src/maxp.cc#L55-L58 came up today (in https://github.com/anexasajoop/farsan/issues/3) and I wonder what it is about :)

**Comment by khaledhosny** [comment]
That is the [maxp](https://www.microsoft.com/typography/otspec/maxp.htm) maxZones.

**Comment by davelab6** [comment]
I don't understand why it would be set to 0

**Comment by khaledhosny** [comment]
The value is read from the font a few lines up, what this code does is basically: if it is 0, set it to one and issue a warning, if it is 3 set it to 2 and issue a warning, in both cases as a workaround for the fonts in the comments. The block of code below that will reject any fonts that don’t have value 1 or 2 after that.

Why a font would set it to 0, I don’t know, the only valid value in the spec are 1 or 2. Seems like a tooling bug.
