### ISSUE TITLE
OTS fails to check for invalid Anchor formats

### ISSUE THREAD

**Issue by gregorkaplan** [khaledhosny/ots#99]
Here, https://github.com/khaledhosny/ots/blob/master/src/gpos.cc#L130, OTS checks for anchor formats 1,2, and 3, but does not check for other values which would be invalid. An example of a font which would currently pass OTS validation, but has invalid Anchor references can be found at https://code.google.com/archive/p/istok/downloads

**Comment by khaledhosny** [comment]
We already reject formats 0 or > 3 a couple of lines above. That link has many fonts, which one(s) do you think has invalid anchor format?

**Comment by behdad** [comment]
This would reject variable fonts BTW.
